### ISSUE TITLE
LLVM compile errors

### ISSUE THREAD

**Issue by vanhauser-thc** [vanhauser-thc/AFLplusplus#1]
Currently only llvm 3.9, 4.0 and 8 compile successfully, 5.0 and 6.0 with a workaround.

Versions 3.7 and 7 fail, workaround is being investigates
And for 5.0 and 6.0 it is to be seen if the g++ workaround can be getting rid of.

 To clarify: this is also in the original afl 2.52b. This is not because of any code additions.

**Comment by hexcoder-** [comment]
A fix has been found. Closing.
