### ISSUE TITLE
Inefficient llvm_mode generated code for neverZero_counters branch

### ISSUE THREAD

**Issue by vanhauser-thc** [vanhauser-thc/AFLplusplus#10]
the shared memory map between afl-fuzz and the target contains 65536 one-byte buckets.

In the current afl implementation these can wrap and in rare occasions result in a 0 byte value which afl-fuzz ignores.

in tests an implementation that saturates (leaves at max 255 value) is bad for performance and bad for path discovery.

An implementation that skips the 0 when wrapping (and goes directly to 1) improves path discovery instead, so this is the road to go.

*Problem*: the code in llvm_mode for this is inefficient.

This is what is generated :
```
mov     al, [r8+r11]
mov     ebx, eax
add     bl, 1
adc     al, 1
mov     [r8+r11], al
```
instead of what would be efficient:
```
mov     al, [r8+r11]
add     al, 1
adc     al, 0
mov     [r8+r11], al
```

Code can be found in https://github.com/vanhauser-thc/AFLplusplus/tree/neverZero_counters (and then in llvm_mode/afl-llvm-pass.so.cc

**Comment by vegard** [comment]
Couldn't you even do something like this to save an instruction?

    mov     al, [r8+r11]
    add     al, 1
    adc     [r8+r11], al

**Comment by vegard** [comment]
Second try :-) Why not do it directly with just 2 instructions:

    add [r8+r11], 1
    adc [r8+r11], 0

**Comment by hexcoder-** [comment]
Yes, I would love to test/benchmark that, but we talk llvm IR here and I could not yet coerce llvm IR into producing that assembler output. Any hints on that?

**Comment by vanhauser-thc** [comment]
Ok this has been resolved. its an issue an llvm and now has a fix:
https://reviews.llvm.org/D64190#change-e3PF3j20UdNS

not sure for which llvm versions that fix will be in - but its nothing we will be able to expect on a system in the next year at a minimum.

@hexcoder- 
Proposal: keep the afl-gcc implementation as the performance impact is minimal and the feature beneficial, and for llvm_mode we keep the env var.
I will rewrite the pass.

and then we merge?

**Comment by hexcoder-** [comment]
ok, fine with me. I will update and then push the portability patch (sed -> tr and version check llvm<->clang)

**Comment by vanhauser-thc** [comment]
done :)
