### ISSUE TITLE
Delivery Method for patches

### ISSUE THREAD

**Issue by domenukk** [vanhauser-thc/AFLplusplus#117]
For the current iteration of unicornafl, I've patched quite a bit:
```bash
❯ git diff --shortstat master unicornafl
65 files changed, 1801 insertions(+), 70 deletions(-)
```
I wonder if creating `.diff` files is still the best way to go. Creating a proper fork for this/these projects might be easier to understand and maintain?
What's everybody's opinion? pro/contra?

**Comment by andreafioraldi** [comment]
1801 insertion including compcov?

**Comment by domenukk** [comment]
Yes. 
This is the current diff:
https://github.com/unicorn-engine/unicorn/compare/master...domenukk:unicornafl
I guess I could pull out a lot of it to header or even c files, making the diffs less ugly - but the question remains.

**Comment by andreafioraldi** [comment]
it depends on how much code is self-contained. the qemu patches are more than 2k loc I guess but a lot of code is self contained and so in the headers. If you can reduce the patches to a decent size and place as much code as possible in the headers is fine to maintain patches.

**Comment by domenukk** [comment]
Do we have good reasons for maintaining the patch sets, though?
With git, fetching upstream patches is not an issue either way and submodules now kinda work. It would get rid of most strange build scripts.

**Comment by andreafioraldi** [comment]
Yep I agree, and Unicorn does not change too often like QEMU so for me it's fine to not ship patches.
@vanhauser-thc @hexcoder- do you agree?

**Comment by hexcoder-** [comment]
Yes, it seems the logical thing to do. Greetings Heiko
--
Diese Nachricht wurde von meinem Android Mobiltelefon mit 1&1 Mail gesendet.

Am 26.11.19, 20:14 schrieb Andrea Fioraldi <notifications@github.com>:

Yep I agree, and Unicorn does not change too often like QEMU so for me it's fine to not ship patches.
@vanhauser-thc @hexcoder- do you agree?

**Comment by vanhauser-thc** [comment]
We have a travis script that will fail when unicorn will not build anymore or if the instrumentation fails because of changes, so I think we are fine with cloning a sub project in the script instead of shipping patches
