### ISSUE TITLE
Move to Python3 (mostly)?

### ISSUE THREAD

**Issue by domenukk** [vanhauser-thc/AFLplusplus#118]
Currently `build_unicorn_support.sh`  installs in python2 by default on linux.
I don't know what the python mutators expect or need.
However, as py2 is no longer supported starting in 40 days or so, I suggest dropping py2 support completely.

**Comment by vanhauser-thc** [comment]
IMHO we should maybe support both?
the python plugin came in via a PR, so it was not done by us and it is not a focus by us. but yeah we have to do something about it I guess.

**Comment by vanhauser-thc** [comment]
for unicorn @andreafioraldi or @domenukk would be best to take care of this, can one of you two own this?

I will take care of the afl-fuzz python plugin.

**Comment by andreafioraldi** [comment]
What has to be done? Simply port the example scripts to py3?

**Comment by vanhauser-thc** [comment]
that and installing python3 instead of python2 I guess. but @domenukk should know better :)

plus downward compatibility if python3 is not availaible (maybe 1404/trusty doesnt have it? dunno)

**Comment by vanhauser-thc** [comment]
I am done with the python mutator, its now python3 compatible (and python3.7 is prefered over 2.7 in the autodetectionin the Makefile)

for unicorn the test.sh script will also need to be updated

**Comment by andreafioraldi** [comment]
```ERROR: Cannot use 'python3', Python 2.4 or later is required.
       Note that Python 3 or later is not yet supported.
       Use --python=/path/to/python to specify a supported Python.
```
The current version of unicorn is too old, we have to wait @domenukk 's patch

**Comment by vanhauser-thc** [comment]
@domenukk when is the patch coming?
if this takes > 5 days to get it all done I would say we release a new version today/tomorrow

**Comment by domenukk** [comment]
I'm on holidays until Monday.
The branch works and is here: https://github.com/domenukk/unicorn/tree/unicornafl?files=1
But the afl++ build scripts still need to be adapted to use the git submodule and not fail Travis.
Also the git history could be cleaned up if you care for these things.
Feel free to adapt the build scripts, release, or wait until Monday/Tuesday :)

**Comment by andreafioraldi** [comment]
Probably it's better not not use git, just download the archive from the
release page like now.

**Comment by domenukk** [comment]
With PR #138 python3 now works fine for unicorn.
While Python Mutators haven't been touched, I will close this issue for now.

**Comment by vanhauser-thc** [comment]
> With PR #138 python3 now works fine for unicorn.
> While Python Mutators haven't been touched, I will close this issue for now.

I had done that seperately 10 days ago. python3 detection plus changes to the mutator part to make it work :)
