### ISSUE TITLE
check_binary error for Mach-O universal binary with 2 architectures

### ISSUE THREAD

**Issue by riusksk** [vanhauser-thc/AFLplusplus#132]
`$ file /usr/local/bin/python3
/usr/local/bin/python3: Mach-O universal binary with 2 architectures: [i386:Mach-O executable i386] [x86_64:Mach-O 64-bit executable x86_64]
/usr/local/bin/python3 (for architecture i386):	Mach-O executable i386
/usr/local/bin/python3 (for architecture x86_64):	Mach-O 64-bit executable x86_64`

$ afl-fuzz -U -i in -o out -m none -- python3 frida_driver.py
afl-fuzz++2.58d based on afl by Michal Zalewski and a big online community
[+] afl++ is maintained by Marc "van Hauser" Heuse, Heiko "hexcoder" Eissfeldt and Andrea Fioraldi
[+] afl++ is open source, get it at https://github.com/vanhauser-thc/AFLplusplus
[+] Power schedules from github.com/mboehme/aflfast
[+] Python Mutator and llvm_mode whitelisting from github.com/choller/afl
[+] afl-tmin fork server patch from github.com/nccgroup/TriforceAFL
[+] MOpt Mutator from github.com/puppet-meteor/MOpt-AFL
[*] Getting to work...
[+] Using exploration-based constant power schedule (EXPLORE)
[+] You have 4 CPU cores and 2 runnable tasks (utilization: 50%).
[+] Try parallel jobs - see /usr/local/share/doc/afl/parallel_fuzzing.txt.
[*] Checking CPU scaling governor...
[*] Setting up output directories...
[+] Output directory exists but deemed OK to reuse.
[*] Deleting old session data...
[+] Output dir cleanup successful.
[*] Scanning 'in'...
[+] No auto-generated dictionary tokens to reuse.
[*] Creating hard links for all input files...
[*] Validating target binary...

[-] PROGRAM ABORT : Program '/usr/local/bin/python3' is not a 64-bit Mach-O binary
         Location : check_binary(), src/afl-fuzz-init.c:1901

**Comment by andreafioraldi** [comment]
Hi @riusksk,
thanks for the issue.
We don't have a macOS machine and the majority of changes regards Apple devices come from external contributors.
As a workaround, simply use /bin/python3, we'll figure out how to fix ASAP.

PS: is python3 working in unicorn mode? We are working on it but it is not supported ATM, it _should_ not work, use python2 for the moment.

**Comment by riusksk** [comment]
yes, run cmd with your frida-js-afl-instr tool : 
`afl-fuzz -U -i in -o out -m none -- python3 frida_driver.py`

I made the following changes:
```
if ((f_data[0] != 0xCF || f_data[1] != 0xFA || f_data[2] != 0xED) 
          && (f_data[0] != 0xCA || f_data[1] != 0xFE || f_data[2] != 0xBA))
    FATAL("Program '%s' is not a 64-bit Mach-O binary", target_path);
```
then the following error occurred:
```
[-] Hmm, looks like the target binary terminated before we could complete a
    handshake with the injected code. Perhaps there is a horrible bug in the
    fuzzer. Poke <afl-users@googlegroups.com> for troubleshooting tips.

[-] PROGRAM ABORT : Fork server handshake failed
         Location : init_forkserver(), src/afl-forkserver.c:457
```

**Comment by andreafioraldi** [comment]
Ah ok, it's the Frida based instrumentation, I was talking about Unicorn mode.
To fuzz closed source binaries on Linux, I suggest QEMU mode.
The Frida instrumentation is an experiment that has to be ported to Android when the Frida guys will fix all the problems with the Stalker, ATM Frida is not really ready for real fuzzing (and it's not my fault, I don't develop that DBI).

As a workaround, I built a fuzzer based on Frida+QBDI for Android (https://github.com/andreafioraldi/frida-qbdi-fuzzer). Always experimental (the mutator is naive and works only with native code), but at least QBDI works.

**Comment by andreafioraldi** [comment]
Never tested frida-js-afl-instr on macOS, it is not supposed to work on such a platform. The test binary is also Linux only, uses Linux.

**Comment by riusksk** [comment]
What problems need to be solved if I want to port it to macOS?

**Comment by andreafioraldi** [comment]
Above all, recompile test.c as a macOS binary. IDK if there are particular issues cause I never tested it on macOS. I'll close this issue cause it is Out-Of-Topic for AFL++.
Thank you for the patch with universal Mach-O files, I pushed it.
