### ISSUE TITLE
qemu_mode broken with new libdislocator

### ISSUE THREAD

**Issue by andreafioraldi** [vanhauser-thc/AFLplusplus#134]
QEMU fails to start when libdislocator is preloaded via AFL_PRELOAD.
GLib complains about alignment (we added posix_memalign recently).
The workaround (and perharbs the correct way to preload libraries in the QEMU guest without affecting QEMU itself) is using QEMU_SET_ENV.

So `QEMU_SET_ENV=LD_PRELOAD=./libdislocator.so ./afl-fuzz -Q ...` is the right way to have QEMU works with the last libdislocator changes.

What should we do? Pivot AFL_PRELOAD to QEMU_SET_ENV? Define AFL_QEMU_PRELOAD? Simply write in the readme to use QEMU_SET_ENV?
IMO the last is better so that the user can also set other env vars for the guest only.

**Comment by vanhauser-thc** [comment]
I think the easy solution is to set/append to QEMU_SET_ENV with AFL_PRELOAD value (and unset AFL_PRELOAD) in afl-fuzz when the -Q flag is used?

The user can use QEMU_SET_ENV anyway.

I would like to avoid yet another env if it can be avoided and the user does not need to know yet another speciality of how to use the tools

**Comment by andreafioraldi** [comment]
Yep this require a bit of thinking, the format is `QEMU_SET_ENV=VAR1=VALUE,VAR2=VALUE,...` and a VALUE with a comma inside may be a problem (idk if there is and escape method).

**Comment by hexcoder-** [comment]
According to the QEMU docs: no quoting mechanism for commas in `QEMU_SET_ENV` (only possible with -E).

**Comment by andreafioraldi** [comment]
The problem here, apart from that we do not want to hook functions in QEMU itself but only in the target (but AFL always did this so it's secondary now), is that the posix_memalign hook in dislocator is broken (and so QEMU complains about it).

**Comment by andreafioraldi** [comment]
For some reasons does not guarantee that the allocated *ptr is a multiple of alignment. I'm investigating.

**Comment by andreafioraldi** [comment]
```MMAP = 0x7ffff7fea000
posix_memalign(0x7fffffffdc90 1024, 2031) [*ptr = 0x7ffff7fea811]

***MEMORY-ERROR***: [13387]: GSlice: assertion failed: aligned_memory == (gpointer) addr
Aborted
```
This stuff will not only completely broke QEMU but also other applications. We cannot guarantee alignment if we shift all the chunks to the end of the mmaped page.

**Comment by andreafioraldi** [comment]
Now, i len is not a multiple of align, I set len as the next multiple of align greater than len.
```
size_t rem = len % align;
if (rem) len += align - rem;
```
IDK if this is a 100% working solution but now qemu runs again without problems.

**Comment by andreafioraldi** [comment]
I close the QEMU-specific issue, regards QEMU_SET_ENV the problem remain cause, generally, we want to preload stuffs in the target not in QEMU itself but we will change the behaviour of the original AFL changing this. IMO this change has to be done, for instance we don't want to log QEMU strcmp with tokencap.

**Comment by vanhauser-thc** [comment]
@andreafioraldi why do you close it then if we still have to do the change in afl-fuzz for AFL_PRELOAD -> QEMU_... ?   :-)

**Comment by andreafioraldi** [comment]
Cause the problem with QEMU is fixed, AFL_PRELOAD=libdislocator.so works in qemu_mode. I'll open another issue for QEMU_SET_ENV tomorrow. IMO we should address different problems in different issue so that we can easily reference problems in commit messages and reference past fixes that introduce new problems.

**Comment by vanhauser-thc** [comment]
ok just wanted to be sure we are not forgetting it :)
