### ISSUE TITLE
AFL_PRELOAD in qemu_mode

### ISSUE THREAD

**Issue by andreafioraldi** [vanhauser-thc/AFLplusplus#136]
Issue to track the fact that AFL_PRELOAD is mapped to LD_PRELOAD and the specified library is preloaded in both afl-qemu-trace and the target program.
With QEMU_SET_ENV we can avoid this and preload the lib only into the target but we cannot let the user to specify a value of AFL_PRELOAD with a comma inside (or otherwise QEMU_SET_ENV will be broken).

My proposal is to:
+ get the value of AFL_PRELOAD, check if there is a comma. If yes, report error to the user.
+ if QEMU_SET_ENV is not defined, set it as QEMU_SET_ENV=LD_PRELOAD=$AFL_PRELOAD
+ check if LD_PRELOAD is already specified in QEMU_SET_ENV, if yes report the error saying that the user have to use only one of the methods.
+ otherwise, append LD_PRELOAD=$AFL_PRELOAD to QEMU_SET_ENV adding a comma-separated field (QEMU_SET_ENV=LD_PRELOAD=$AFL_PRELOAD,$QEMU_SET_ENV)

**Comment by vanhauser-thc** [comment]
I would add that you only have to add a comma to QEMU_SET_ENV if its already defined.
otherwise sounds good!

**Comment by vanhauser-thc** [comment]
as I was just added a library I added this code. @andreafioraldi you care to check?
