### ISSUE TITLE
llvm_mode make "Prerequisites are not met" with llvm10

### ISSUE THREAD

**Issue by attekett** [vanhauser-thc/AFLplusplus#139]
I'm using llvm10 from Ubuntu Bionic PPA: http://apt.llvm.org/bionic/

I used to change the llvm_mode Makefile to use c++14 when using llvm10, but recently a patch came out to support llvm10. \o/

The patch seems to have some problem, or there is some incompatibility I'm not aware of.

`
:/AFLplusplus/llvm_mode$ make
Makefile:51: llvm_mode only supports llvm versions 3.8.0 up to 10
llvm_mode detected llvm 10+, enabling neverZero implementation and c++14
Prerequisites are not met, skipping build

:/AFLplusplus/llvm_mode$ llvm-config --version
10.0.0

:/AFLplusplus/llvm_mode$ clang --version
clang version 10.0.0-+20191211091425+f99297176cd-1~exp1~20191211082036.1372
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
`

From the make output it looks like Makefile detected that I have llvm10, set configuration for it and then exited as unsupported.

If I set the LLVM_UNSUPPORTED test from Makefile:39 to always pass, the build seems to work without any problems. 

Is the Makefile check incorrect, or is there some issues with llvm10, even though the build passes?

**Comment by vanhauser-thc** [comment]
@attekett there is now a fix in the git, does it work for you with that?

**Comment by vanhauser-thc** [comment]
@attekett  - please test, we want to release a new version.

**Comment by attekett** [comment]
@vanhauser-thc Sorry, didn't realize you were waiting for this. Got hit by a really nasty flu and been on sick leave for couple of days.

I tested the build process and did a quick run with a random target. Everything works as it should.

```
commit 7218afdd8ea47f8ce83f98c51d2656a846b7fd49 (HEAD -> master, origin/master, origin/HEAD)
Author: Andrea Fioraldi <andreafioraldi@gmail.com>
Date:   Mon Dec 16 14:31:16 2019 +0100
```

```
AFLplusplus/llvm_mode$ make
llvm_mode detected llvm 10+, enabling neverZero implementation and c++14
[+] shmat seems to be working.
[*] Checking for working 'llvm-config'...
[*] Checking for working '/usr/lib/llvm-10/bin/clang'...
[*] Checking for matching versions of '/usr/lib/llvm-10/bin/clang' and 'llvm-config'
[!] WARNING: we have llvm-config version 10.0.0 and a clang version
[!] Retrying with the clang compiler from llvm: CC=/usr/lib/llvm-10/bin/clang
[*] Checking for '../afl-showmap'...
[+] All set and ready to build.
...
[*] Building 32-bit variant of the runtime (-m32)... success!
[*] Building 64-bit variant of the runtime (-m64)... success!
...
[*] Testing the CC wrapper and instrumentation output...
...
[+] All right, the instrumentation seems to be working!
[+] All done! You can now use '../afl-clang-fast' to compile programs.
```

**Comment by vanhauser-thc** [comment]
thanks for testing and get well :)
