### ISSUE TITLE
AFL_BENCH_JUST_ONE=1 has no effect

### ISSUE THREAD

**Issue by domenukk** [vanhauser-thc/AFLplusplus#141]
If I understand correctly (and skimming through the code), this:
```bash
❯ AFL_BENCH_JUST_ONE=1 ../afl-fuzz -U -i in -o out -d -- python ../unicorn_mode/samples/simple/simple_test_harness.py @@
```
Should run only one testcase, however it just spawns AFL++ normally
Or am I holding it wrong?

**Comment by andreafioraldi** [comment]
I'm not sure, but bench one should be a complete run of fuzz_one on the first input, so there are many runs

**Comment by domenukk** [comment]
Aah so it's not one single run but one single testcase with one iteration.
My bad, sorry.
