### ISSUE TITLE
Unsigaction does not compile with -m32

### ISSUE THREAD

**Issue by floyd-fuh** [vanhauser-thc/AFLplusplus#144]
hi there,

I'm trying to build qemu-mode and the unsigaction in it (actually just running make binary-only). However, I get:

```
[+] Building unsigaction ...
make[1]: Entering directory '/afl/qemu_mode/unsigaction'
cc -m32 -fPIC -shared unsigaction.c -o unsigaction32.so || echo "Cannot build unsigation32"
/usr/bin/ld: cannot find crti.o: No such file or directory
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/9/libgcc.a when searching for -lgcc
/usr/bin/ld: cannot find -lgcc
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/9/libgcc.a when searching for -lgcc
/usr/bin/ld: cannot find -lgcc
collect2: error: ld returned 1 exit status
```

in Ubuntu 19.10. This seems to assume that -m32 just works. Is this working as intended? At other places AFL++ checks if -m32 works and if not just goes with -m64... https://github.com/vanhauser-thc/AFLplusplus/blob/624f0da6c0f7034cc56784d4b971b2c12ad5aa98/llvm_mode/Makefile#L222

**Comment by andreafioraldi** [comment]
Just the redirection to /dev/null is missing. You don't have the x86 libs in your Ubuntu, it fails gracefully with the `|| echo 'Cannot build....`.

**Comment by floyd-fuh** [comment]
I see. So installing lib32gcc-9-dev should do the trick I guess

**Comment by andreafioraldi** [comment]
yes. I beautified the error now.
