### ISSUE TITLE
NtH: Update docs to Markdown

### ISSUE THREAD

**Issue by ThomasTNO** [vanhauser-thc/AFLplusplus#145]
Currently the documentation of AFLplusplus is writing in plain text.

I suggest to reformat the docs/*.txt files to markdown.

What are your thoughts?

**Comment by vanhauser-thc** [comment]
if you want to do that - sure, go for it :)

**Comment by ThomasTNO** [comment]
Alright, I made a start. Could you provide access so that I can push my docs_to_md branch?

**Comment by andreafioraldi** [comment]
Just fork the repo and open a pull request

**Comment by vanhauser-thc** [comment]
@ThomasTNO just click fork repo - make your changes in your fork, and then click "create pull request" on your fork. super easy.

**Comment by domenukk** [comment]
This was mostly fixed with commit 89088035322c8b3ddb07f29367f62cdb590fb8f5
