### ISSUE TITLE
havoc/custom is not a good choice to have in the same line in stats

### ISSUE THREAD

**Issue by andreafioraldi** [vanhauser-thc/AFLplusplus#147]
![Screenshot at 2019-12-19 11-47-06](https://user-images.githubusercontent.com/16168186/71167683-6dec7900-2255-11ea-836f-5bdb16c4691f.png)

This is what I was saying sometine ago when it was instroduced. We should find a solution cause is very ugly.

**Comment by vanhauser-thc** [comment]
yeah ... what do you propose?
I would like to to change it too much - maybe a vertical line in the middle of the yields and there we put one custom per line?

**Comment by andreafioraldi** [comment]
Is custom completely alternative to havoc? if yes, we can just show only havoc and only custom when it is enabled

**Comment by andreafioraldi** [comment]
![Screenshot at 2019-12-19 14-17-52](https://user-images.githubusercontent.com/16168186/71176552-62f01380-226a-11ea-88fa-f74ba049f5d1.png)

An additional line is not so bad, it is the same number of lines cause the cpu000 was a line after the status screen

**Comment by andreafioraldi** [comment]
and I also propose havoc/radamsa and py/custom

**Comment by andreafioraldi** [comment]
![Screenshot at 2019-12-19 14-23-12](https://user-images.githubusercontent.com/16168186/71176909-1c4ee900-226b-11ea-855d-05d463dcbcde.png)

**Comment by vanhauser-thc** [comment]
fine with me. for the havoc/rad line, please rename it "havor/slice/rad" (slide is the 2nd o fthe three in your picture)

**Comment by andreafioraldi** [comment]
havoc/splice/rad probably will not fit into the space. original AFL has only havioc for havoc/splice

**Comment by andreafioraldi** [comment]
![Screenshot at 2019-12-19 14-33-12](https://user-images.githubusercontent.com/16168186/71177531-85832c00-226c-11ea-934d-ad99572eaf7c.png)

mmm no, neither havoc/splice/R.

havoc/rad seems fine to me cause consistent with AFL.

**Comment by andreafioraldi** [comment]
I'll push this as it is now, maybe you'll find another solution.
