### ISSUE TITLE
Build mode QBDI

### ISSUE THREAD

**Issue by linhlhq** [vanhauser-thc/AFLplusplus#149]
Hi, I used to fuzzing android nativelib, but I got this error. Can anyone fix it for me? Thanks.
![Screen Shot 2019-12-21 at 12 32 57 PM](https://user-images.githubusercontent.com/28854132/71303651-4f6db580-23ee-11ea-8bdc-97c529dc75ed.png)

**Comment by vanhauser-thc** [comment]
@hac425xxx  -  your code, can you help?

**Comment by andreafioraldi** [comment]
You're using a too old Android API. If you google, you can easily see that __register_atfork was introduced with API level >= 23.

**Comment by andreafioraldi** [comment]
So the problem is that you want to run something compiled with a recent NDK on an old device

**Comment by linhlhq** [comment]
thanks all, I switched to api >= 23 and fixed this error :D.
