### ISSUE TITLE
MOpt-AFL mutations selection optimization

### ISSUE THREAD

**Issue by andreafioraldi** [vanhauser-thc/AFLplusplus#15]
```MOpt-AFL is a AFL-based fuzzer that utilizes a customized Particle Swarm Optimization (PSO) algorithm to find the optimal selection probability distribution of operators with respect to fuzzing effectiveness.```

https://github.com/puppet-meteor/MOpt-AFL

This seems very interesting and the results showed in the paper confirm the validity of this technique. It does not change the way about how AFL works and maybe can be integrated here with a bit of source code refactoring.

**Comment by andreafioraldi** [comment]
A good idea is to ask directly to the authors if they want merge they changes to AFL directly here.

**Comment by hexcoder-** [comment]
I don't understand the issue here. MOpt is already included, first in branch MOpt and then merged to master...

**Comment by andreafioraldi** [comment]
Lol I missed it, GG for the rapid merge

**Comment by vanhauser-thc** [comment]
yes I think @andreafioraldi missed it :)

I did a lot of testing and verified that MOpt is really good and then added it

also instrim is now in trunk/master. makes llvm_mode much, much faster (but slightly lower coverage)

**Comment by vanhauser-thc** [comment]
@andreafioraldi but if you ever see something interested, integrate it or create an issue. I always look and @hexcoder- too, but of course we can miss stuff :)
