### ISSUE TITLE
Build error with old LLVM versions

### ISSUE THREAD

**Issue by andreafioraldi** [vanhauser-thc/AFLplusplus#151]
Look at the xenial-arm64 Travis build:
```c
afl-llvm-pass.so.cc:39:10: fatal error: 'llvm/IR/DebugInfo.h' file not found

#include "llvm/IR/DebugInfo.h"
```

Seems that with old LLVM the header is `llvm/DebugInfo.h".

Note that this header is not included in original AFL, so probably we broken the compatibility woth LLVM < 3.7.
I say 3.7 cause is the first version with the header inside IR that I've found googling.

This needs more investigation, as a quick fix I added
```c
#include <llvm/Config/llvm-config.h>

#if (LLVM_VERSION_MAJOR <= 3) && (LLVM_VERSION_MINOR < 7)
#include <llvm/DebugInfo.h>
#else
#include <llvm/IR/DebugInfo.h>
#endif
```

But I'm not sure about the LLVM version.

**Comment by andreafioraldi** [comment]
Not working fix. `llvm/Config/llvm-config.h` is not present in old llvms. We have to manage it in the Makefile.

**Comment by devnexen** [comment]
Just curious until how far it needs to support old LLVM versions ? egg, LLVM 3.7 2015

**Comment by andreafioraldi** [comment]
I don't really know but a Travis build (ubuntu 16.04) fails to build LLVM mode with this errors.

**Comment by andreafioraldi** [comment]
And this is strange cause clang-6 is installed but probably the script is using the wrong llvm-config and it is not using LLVM 6 but the Ubuntu 16.04 default one.

**Comment by andreafioraldi** [comment]
A fix can be also to decide to not support these LLVM versions and fix Travis

**Comment by vanhauser-thc** [comment]
I would not like to drop the support. there are still people out there who test on specific configurations (where their old software they still have to maintain is running).
that being said - I think afl only supported 3.8 onwards anyway?
@hexcoder- you should know :)

**Comment by hexcoder-** [comment]
The first working llvm_mode from original afl was with llvm 3.4, but since then we have modified some places (in AFL++). I tested always with stock ubuntu 16.04 supplied llvm 3.8.0. I will check, how llvm 3.4 cooperates with AFL++.

**Comment by hexcoder-** [comment]
I am currently investigating llvm_mode with llvm 3.4. It is sort of retro-computing...
So please do not change source files in llvm_mode right now, thanks (makes my live easier)!

afl-llvm-pass.so.cc and laf-intel passes seem to be changable, but the LLVMInsTrim path uses
`DominatorTreeWrapperPass`, which is not available in version 3.4.

When I get 3.4 running, I will also check with llvm versions 3.5, 3.6, 3.7.

**Comment by hexcoder-** [comment]
Of course you had to change something in llvm_mode despite my wish, sigh.

First results are there (ceed66930ef15922cd25e70a4770eaa31309e0ce). I had to downgrade some code.

- There is now complete support for llvm 3.8.0 and up. `make tests` has no fails.

- 3.7.1 works with the exception of LLVMInsTrim, which uses modern extensions. So I adapted the Makefile to ignore this error and continue building the other passes. `make tests` has one fail for the InsTrim feature.

- 3.4, 3.5, 3.6 compile llvm_mode with the exception of LLVMInsTrim, but fail to load the .so passes
(probably some stupid error).`make tests` has all fails.

@andreafioraldi: llvm/Config/llvm-config.h is generally present on older llvm versions (even on my 3.4), but not in our xenial-arm64 travis build it seems. I do not understand, why.
I want that fixed, but have no access to the travis-build environment. The reason is: I want to see the afl-cmin tests on arm64 (which currently depend on a working llvm_mode) in travis.

**Comment by andreafioraldi** [comment]
Marc is the Travis guy, I don't even know if you can get a shell on Travis, probably not.

**Comment by hexcoder-** [comment]
Yeah, Marc can, we cannot. I could build a VM, but that is too much work for now.

**Comment by vanhauser-thc** [comment]
it is possible to get a shell. but anyone of you can too -> fork, and register that fork for travis. write an email to support@travis and say you need debug shell access. thats it.

but they build upon standard minimal ubuntu. it should be simple to build that in a docker container as well

**Comment by vanhauser-thc** [comment]
is this issue still open?

**Comment by hexcoder-** [comment]
One open point is:
llvm/Config/llvm-config.h is generally present on older llvm versions (even on my 3.4), but not in our xenial-arm64 travis build it seems. I do not understand, why.
I want that fixed.

This currently prohibits llvm_mode on arm64 there.

**Comment by vanhauser-thc** [comment]
I added some debug output to arm64 travis output - maybe that helps you:
```
find / -name llvm-config.h
apt-cache search clang | grep clang-
apt-cache search llvm | grep llvm-
dpkg -l | egrep 'clang|llvm'
```

**Comment by hexcoder-** [comment]
Thanks, you fixed it!.

**Comment by vanhauser-thc** [comment]
@hexcoder- for travis I set hard:

```
LLVM_CONFIG=llvm-config-6.0
```
The LLVM config file lies in:
```
/usr/include/llvm-6.0/llvm/Config/llvm-config.h
```
and now llvm_mode works:
https://travis-ci.com/vanhauser-thc/AFLplusplus/jobs/289760791
