### ISSUE TITLE
AFL_LLVM_LAF_SPLIT_FLOATS breaks bogofilter

### ISSUE THREAD

**Issue by floyd-fuh** [vanhauser-thc/AFLplusplus#155]
When compiling the bogofilter project from sourceforge, AFL_LLVM_LAF_SPLIT_COMPARES breaks the binary. Although the first run of the binary will work as expected, because the bogofilter home directory is not yet populated, the second invocation will result in an abort:

```
$ /targets/bogofilter-1.2.5/build-afl/src/bogofilter -e -u -p -d ./home_bogofilter/ < /targets/bogofilter-1.2.5/src/tests/inputs/dump.load.inp
gsl: ../../src/../gsl/specfunc/gamma_inc.c:449: ERROR: domain error
Default GSL error handler invoked.
Aborted
```

This looks like https://github.com/ampl/gsl/blob/master/specfunc/gamma_inc.c#L503 is hit with the AFL binary:

```
int
gsl_sf_gamma_inc_Q_e(const double a, const double x, gsl_sf_result * result)
{
  if(a < 0.0 || x < 0.0) {
    DOMAIN_ERROR(result);
  }
```

AFL binary with ASAN has the same problem. Vanilla clang and clang-ASAN binary with no AFL involvement work as expected and do not produce the above error.

Doing an `unset AFL_LLVM_LAF_SPLIT_COMPARES AFL_LLVM_LAF_SPLIT_FLOATS` before compiling with `cd build-afl && CC=afl-clang-fast CXX=afl-clang-fast++ CFLAGS="-Wno-error" ../configure && CFLAGS="-Wno-error" make && cd ..` creates a valid binary that does not have the problem. I expected that because this looked like a split-compare issue and it seems to be one. Do you agree?

Let me know if you need any further information.

**Comment by hexcoder-** [comment]
Thanks, that depends on AFL_LLVM_LAF_SPLIT_FLOATS=1, so the error is confirmed.

I could not reproduce with only AFL_LLVM_LAF_SPLIT_COMPARES=1 set (like the title suggested).
Will investigate...

**Comment by floyd-fuh** [comment]
oh yeah, sorry about that, it is really AFL_LLVM_LAF_SPLIT_FLOATS of course (I enabled it by default in my docker image...)

**Comment by hexcoder-** [comment]
So, i think i fixed the issue with commit https://github.com/vanhauser-thc/AFLplusplus/commit/064cd3315c2c31a26eef5fd0f70d6fd2c77ef0f8. Could you please retest?
Thanks!

**Comment by floyd-fuh** [comment]
This seems to have fixed it, thank you!

Btw. we haven't announced it yet, but there is https://github.com/pentagridsec/5-AFL-suite-docker now. I can recommend using containers, it makes it much easier to get reproducible builds and realizing things about dependencies.

**Comment by hexcoder-** [comment]
Great! We should add that to our docs after the official announcement.
