### ISSUE TITLE
afl-tmin always reduces to zero bytes

### ISSUE THREAD

**Issue by floyd-fuh** [vanhauser-thc/AFLplusplus#159]
It was a pleasure to meet most of you at 36C3 :)

I just ran into a problem with afl-tmin and I just can't wrap my head around why it would behave like it does. Target was bogofilter again.

First of all, I did a fuzzing run with an afl binary, then with an afl-ASAN binary of bogofilter. After the fix in https://github.com/vanhauser-thc/AFLplusplus/issues/155 this seemed to work all as expected, paths were founds, but only a "false positive" crash (due to memory limitation). However, I wanted to minimize the queue. So I ran afl-cmin.py which worked. Now I also wanted to minimize the queue entries with afl-tmin. However, all files were reduced to zero bytes, so I started digging into it:

```
# afl-showmap -o /dev/null -m 3000 -t 3000 -- /targets/bogofilter-1.2.5/build-afl/src/bogofilter -e -u -p -d ./home_bogofilter/ < /targets/afl_cmined/fff520db4a795a755206417e3d2fb80e6f945bd2 
afl-showmap++2.59d by Michal Zalewski
[*] Executing '/targets/bogofilter-1.2.5/build-afl/src/bogofilter'...

-- Program output begins --
[...]snip[...]
-- Program output ends --
[+] Captured 6316 tuples (highest value 8, total values 23176) in '/dev/null'.
```

Same result (6316 tuples) when run again and again (binary is stable).

Let's look at a different input file:

```
# afl-showmap -o /dev/null -m 3000 -t 3000 -- /targets/bogofilter-1.2.5/build-afl/src/bogofilter -e -u -p -d ./home_bogofilter/ < /targets/afl_cmined/0f27ae39e5d8a2d0051c8cad6f58afaa52186fad |less
afl-showmap++2.59d by Michal Zalewski
[*] Executing '/targets/bogofilter-1.2.5/build-afl/src/bogofilter'...

-- Program output begins --
[...]snip[...]
-- Program output ends --
[+] Captured 6022 tuples (highest value 8, total values 22295) in '/dev/null'.
```

Ok, this time another result (6022 tuples), but again when run again and again stable.

Ok, what if we feed an empty file instead?

```
# touch /targets/empty
# afl-showmap -o /dev/null -m 3000 -t 3000 -- /targets/bogofilter-1.2.5/build-afl/src/bogofilter -e -u -p -d ./home_bogofilter/ < /targets/empty                                              
afl-showmap++2.59d by Michal Zalewski
[*] Executing '/targets/bogofilter-1.2.5/build-afl/src/bogofilter'...

-- Program output begins --
X-Bogosity: Spam, tests=bogofilter, spamicity=0.000000, version=1.2.5

-- Program output ends --
[+] Captured 3579 tuples (highest value 8, total values 5368) in '/dev/null'.
```

So far so good, all fine and how I expect it to be. However, afl-tmin tells me:

```
# afl-tmin -i /targets/afl_cmined/0f2c599c8a56ffd0eb78078770246d5641149f52 -o /targets/cmined_tmined/0f2c599c8a56ffd0eb78078770246d5641149f52 -t 3000 -m 3000 -- /targets/bogofilter-1.2.5/build-afl/src/bogofilter -e -u -p -d ./home_bogofilter/
afl-tmin++2.59d by Michal Zalewski

[+] Read 4662 bytes from '/targets/afl_cmined/0f2c599c8a56ffd0eb78078770246d5641149f52'.
[*] Spinning up the fork server...
[+] All right - fork server is up.
[*] Performing dry run (mem limit = 3000 MB, timeout = 3000 ms)...
[+] Program terminates normally, minimizing in instrumented mode.
[*] Stage #0: One-time block normalization...
[+] Block normalization complete, 4662 bytes replaced.
[*] --- Pass #1 ---
[*] Stage #1: Removing blocks of data...
    Block length = 512, remaining size = 4662
[+] Block removal complete, 4662 bytes deleted.
[!] WARNING: Down to zero bytes - check the command line and mem limit!
[*] Stage #2: Minimizing symbols (0 code points)...
[+] Symbol minimization finished, 0 symbols (0 bytes) replaced.
[*] Stage #3: Character minimization...
[+] Character minimization done, 0 bytes replaced.
[*] --- Pass #2 ---
[*] Stage #1: Removing blocks of data...
    Block length = 1, remaining size = 0
[+] Block removal complete, 0 bytes deleted.

     File size reduced by : 100.00% (to 0 bytes)
    Characters simplified : 466200.00%
     Number of execs done : 84
          Fruitless execs : path=0 crash=0 hang=0

[*] Writing output to '/targets/cmined_tmined/0f2c599c8a56ffd0eb78078770246d5641149f52'...
[+] We're done here. Have a nice day!
```

So it minimized it to zero bytes, which it shouldn't because obviously the tuples for an empty file are not the same. And the same problem for the other file (`fff520db4a795a755206417e3d2fb80e6f945bd2`) and all others. afl-tmin should do stdin by default and afl-fuzz does as well and worked just fine. Any ideas why afl-cmin, afl-fuzz and afl-showmap work fine but afl-tmin is broken?

It could be something like afl-tmin not feeding to stdin correctly or something...

Also: Could you add the feature that afl-tmin prints on how many tuples are found during the first run with the input? That would help to know if at least the initial run was correct.

**Comment by vanhauser-thc** [comment]
I can reproduce the problem, and its not only present for bogofilter, but a generic bug in afl-tmin.

```
afl-gcc -o test-instr test-instr.c
mkdir in
echo foooooooooo > in
afl-tmin -i in -o out ./test-instr
```

@andreafioraldi @hexcoder- not sure how much time I will have the next days, if you can also have a look

@floyd-fuh - for futures issue please give a download url for the target plus building command and example files that trigger the issue. this took me quite a while to get it all together

**Comment by vanhauser-thc** [comment]
I have located the bug - afl-tmin uses afl-forkserver.c, and that produces wrong results in the trace_bits.

afl-showmap and afl-simulate show both the same values, where as if you put a trace_bits dump in afl-tmin it shows different data in the map. and that data in the map stays always the same although its nulled in between.

if I disable forkserver.h in afl-tmin and uncomment the one that is in afl-tmin it works correctly.

ergo: afl-forkserver has an issue, which does not come up when afl-fuzz uses is though.

**Comment by vanhauser-thc** [comment]
found the bug and fixed it.

I will now add two test cases for the test framework, one for afl-cmin and one for afl-tmin so we will find such issues in the future via travis

**Comment by vanhauser-thc** [comment]
test cases added.
@floyd-fuh  can you please verify that the fix works for you?

**Comment by floyd-fuh** [comment]
Thank you, that fixed the issue!

**Comment by xxrz** [comment]
Hello, sorry to bother you. I want to know how this problem was solved in the end? I also have this problem when using afl-tmin in afl++ docker.

**Comment by vanhauser-thc** [comment]
@xxrz there is no such bug for a long time.are you using a totally outdated docker image?
otherwise it is your target that does not like your inputs.

**Comment by xxrz** [comment]
Hello, thank you for your reply. According to your answer, I switched to the latest version of docker，but still get the same error. My target is a simple example:
> int vuln(char *Data) {
> if(Data[0] == 'C')
> {
>     printf("It is bugggggggggggg!\n");
    raise(SIGSEGV);
}
else if(Data[0] == 'F')
{
    printf("It is paht2!\n");
}
else{
    printf("It is path3!\n");
}
return 0;
}

My testcases are "Caa" and "aaa." But the final result obtained by using afl-tmin is "Down to zero bytes." I don't understand why this happens. Can you answer my question?

**Comment by vanhauser-thc** [comment]
I cant answer any question if you do not supply the full program. likely you have a bug in the function that calls vuln().

**Comment by xxrz** [comment]
Thank you for your reply, the complete test program is [here](https://github.com/xxrz/test/tree/master/demo).
