### ISSUE TITLE
llvm_mode/README.instrim missing

### ISSUE THREAD

**Issue by dkasak** [vanhauser-thc/AFLplusplus#16]
The file `llvm_mode/README.instrim` is mentioned [here](https://github.com/vanhauser-thc/AFLplusplus/blob/0af9f664db5b68e1eb8daa5257410f2e9c400076/docs/env_variables.txt#L123) but it appears it's not committed.

**Comment by vanhauser-thc** [comment]
correct, that got lost when a commit fuckup happened. luckily I still have it, its in now.

**Comment by vanhauser-thc** [comment]
thanks!
