### ISSUE TITLE
afl-tmin tests also fail on NetBSD

### ISSUE THREAD

**Issue by hexcoder-** [vanhauser-thc/AFLplusplus#165]
will deliever details after work...

**Comment by hexcoder-** [comment]
increased memory to 200 megs. That fixed it.

**Comment by vanhauser-thc** [comment]
what is wrong with netbsd? how can a simple small binary - I mean only true and false binaries are smaller, right - how can this require 200mb of memory??? This isnt Windows 10 ...

**Comment by hexcoder-** [comment]
@krytarowski: It would be good, if you could confirm my results (running afl-showmap and afl-tmin with -m100 on the very small test program).
If the results are correct, could you enlighten us, why we need such a high memory limit on NetBSD?

Thanks

**Comment by krytarowski** [comment]
Please share the exact procedure (ideally command by command) how to reproduce your problem.

**Comment by andreafioraldi** [comment]
Just speculation: maybe something related to the loader? Probably it maps more memory but don't use it (so the kernel doesn't allocate frames for it) but it is detected by rlimit? We can just add a workaround that sets to 200 the default memory limit on NetBSD in config.h

**Comment by hexcoder-** [comment]
@krytarowski: will do in the evening after work .

**Comment by hexcoder-** [comment]
@krytarowski: ok, here is my command list (i am on NetBSD 8.0 in VirtualBox):
make
cd test
../afl-gcc -o test-instr.plain ../test-instr.c
mkdir in in2
echo 000000000000000000000000 > in/in2
../afl-tmin -i in/in2 -o in2/in2 -- ./test-instr.plain

gives
```
fl-tmin++2.60d by Michal Zalewski

[+] Read 25 bytes from 'in/in2'.
[*] Spinning up the fork server...

[-] Hmm, looks like the target binary terminated before we could complete a
    handshake with the injected code. There are two probable explanations:

    - The current memory limit (50.0 MB) is too restrictive, causing an OOM
      fault in the dynamic linker. This can be fixed with the -m option. A
      simple way to confirm the diagnosis may be:

      ( ulimit -Sd $[49 << 10]; /path/to/fuzzed_app )

      Tip: you can use http://jwilk.net/software/recidivm to quickly
      estimate the required amount of virtual memory for the binary.

    - Less likely, there is a horrible bug in the fuzzer. If other options
      fail, poke <afl-users@googlegroups.com> for troubleshooting tips.

[-] PROGRAM ABORT : Fork server handshake failed
         Location : init_forkserver(), src/afl-forkserver.c:461
```

**Comment by hexcoder-** [comment]
-m122 or more will work with afl-tmin.
`ulimit -Sd 2; ./test-instr.plain` or more will work with the test program directly.

**Comment by vanhauser-thc** [comment]
out of curiosity, could you pleas execute:
```
ls -l test-instr.plain
ldd test-instr.plain | grep = | awk '{print$3}' | xargs ls -lL 
```
maybe its the shared libraries that are so big ...

**Comment by hexcoder-** [comment]
Good idea to check, but I don't think so:

```
localhost$ ls -l test-instr.plain 
-rwxr-xr-x  1 heiko  users  13256 Jan  8 00:26 test-instr.plain
localhost$ ldd test-instr.plain | grep = | awk '{print$3}' | xargs ls -lL
-r--r--r--  1 root  wheel  1568800 Jul 17  2018 /usr/lib/libc.so.12

```

**Comment by vanhauser-thc** [comment]
in my opinion this is resolved (as in: its not our fault and it works).
@hexcoder- ?
@krytarowski any idea why the memory requirements are so high? I doubt there is anything we can change, but an understanding why would help :)

**Comment by krytarowski** [comment]
I have reproduced the issue. I will try to research it.

**Comment by krytarowski** [comment]
This is likely a NetBSD kernel bug. There is a similar issue documented in syzkaller:

```static void sandbox_common()
{
        if (setsid() == -1)
                fail("setsid failed");

        // Some minimal sandboxing.
        struct rlimit rlim;
#ifdef GOOS_freebsd
        // Documented bug in OpenBSD.
        // This causes frequent random aborts. Reason unknown.

        // This also causes ENOMEM on NetBSD during early init.
        rlim.rlim_cur = rlim.rlim_max = 128 << 20;
        setrlimit(RLIMIT_AS, &rlim);
#endif
        rlim.rlim_cur = rlim.rlim_max = 8 << 20;
        setrlimit(RLIMIT_MEMLOCK, &rlim);
        rlim.rlim_cur = rlim.rlim_max = 1 << 20;
        setrlimit(RLIMIT_FSIZE, &rlim);
        rlim.rlim_cur = rlim.rlim_max = 1 << 20;
        setrlimit(RLIMIT_STACK, &rlim);
        rlim.rlim_cur = rlim.rlim_max = 0;
        setrlimit(RLIMIT_CORE, &rlim);
        rlim.rlim_cur = rlim.rlim_max = 256; // see kMaxFd
        setrlimit(RLIMIT_NOFILE, &rlim);
}

```

**Comment by krytarowski** [comment]
I will try to find a small reproducer in a standalone C program and check if this can be fixed.

**Comment by vanhauser-thc** [comment]
OK, then we know its a NetBSD bug.
which means even if it is fixed we dont know if the kernel that is used on the target would be a fixed version or not - hence we have to leave the workaround in it.

@hexcoder- maybe we should add an #ifdef NETBSD to afl-fuzz that increases the memory limits by default?

**Comment by krytarowski** [comment]
```
147 kamil@chieftec /tmp $ cat test.c                                                                  
#include <sys/resource.h>
#include <unistd.h>

int
main(int argc, char **argv)
{
        struct rlimit rlim;
        rlim.rlim_cur = rlim.rlim_max = 100 << 20;
        setrlimit(RLIMIT_AS, &rlim);

        execl("/bin/echo", "/bin/echo", NULL);
}
148 kamil@chieftec /tmp $ gcc test.c                                                                  
149 kamil@chieftec /tmp $ ./a.out                                                                     
Cannot map anonymous memoryCannot allocate memory: Cannot allocate memory
```

**Comment by hexcoder-** [comment]
@vanhauser-thc : Yes, that is better than to change the tests.

**Comment by krytarowski** [comment]
OK, on execve() the vm_map.size is 125MB for some reason.

```
(gdb) p p->p_vmspace->vm_map.size >> 20
$18 = 125
(gdb) bt
#0  uvm_mmap (map=0xffffaf5096cc15c0, addr=0xffffd00032fecea0, size=32768, prot=3, maxprot=3, flags=4098, advice=0, uobj=0x0, foff=0, 
    locklimit=334890325) at /usr/src/sys/uvm/uvm_mmap.c:881
#1  0xffffffff80d57e95 in sys_mmap (l=0xffffaf5098831000, uap=0xffffd00032fed000, retval=0xffffd00032fecfe0) at /usr/src/sys/uvm/uvm_mmap.c:401
#2  0xffffffff8026d851 in sy_call (sy=0xffffffff81e5e378 <sysent+4728>, l=0xffffaf5098831000, uap=0xffffd00032fed000, rval=0xffffd00032fecfe0)
    at /usr/src/sys/sys/syscallvar.h:65
#3  0xffffffff8026d93d in sy_invoke (sy=0xffffffff81e5e378 <sysent+4728>, l=0xffffaf5098831000, uap=0xffffd00032fed000, rval=0xffffd00032fecfe0, 
    code=197) at /usr/src/sys/sys/syscallvar.h:94
#4  0xffffffff8026dd08 in syscall (frame=0xffffd00032fed000) at /usr/src/sys/arch/x86/x86/syscall.c:138
#5  0xffffffff802096ad in handle_syscall ()
```

Investigating.

**Comment by hexcoder-** [comment]
Changed the afl-tmin test back to default memory limit, and increased the default in config.h for NetBSD, so afl-fuzz, afl-tmin, afl-showmap, etc. will get it.
From my point of view this issue can be closed now.

**Comment by krytarowski** [comment]
I think that address space has prereserved ~128 MB for stack and this causes ENOMEM. That memory is by default unused (lazily allocated) and not taking any physical pages. So limiting RLIMIT_AS on NetBSD for small values below 200MB has little point.

**Comment by vanhauser-thc** [comment]
its not a bug but a, well, kinda a feature. so we need the workaround in afl-fuzz.
hexcoder did all the work, so lets close this :)

**Comment by hexcoder-** [comment]
@krytarowski: thanks for your evaluation! Now we know the reason.
