### ISSUE TITLE
compiling fuzzer-test-suite: "afl-llvm-rt.o.c: 'config.h' not found" (but afl-2.52b works)

### ISSUE THREAD

**Issue by egueler** [vanhauser-thc/AFLplusplus#169]
I'm trying to build Google's [fuzzer-test-suite](https://github.com/google/fuzzer-test-suite) with afl++ but it keeps complaining that "config.h" is missing. But when I try the same steps with afl-2.52b, it works.

I created a bash script to reproduce my steps:

[setup.sh.zip](https://github.com/vanhauser-thc/AFLplusplus/files/4041496/setup.sh.zip)

Calling it with "./setup.sh afl" (which builds afl-2.52b) works, but "./setup.sh afl++" does not, producing:

> Building with afl
aflpp_bug/dl/afl//llvm_mode/afl-llvm-rt.o.c:26:10: fatal error: 'config.h' file not found
#include "config.h"
         ^~~~~~~~~~
1 error generated.

Although I'm trying to compile "boringssl-2016-02-12" in the script, the problem is not unique to this library (the only other one I tested, guetzli-2017-3-30, has the same error).

My clang:
> clang --version
> clang version 9.0.1-+20191211110317+c1a0a213378-1~exp1~20191211221711.104 
> Target: x86_64-pc-linux-gnu
> Thread model: posix
> InstalledDir: /usr/bin

Any ideas?

**Comment by andreafioraldi** [comment]
-I aflpp_bug/dl/afl/include is missing. We included it in llvm_mode/Makefile

**Comment by andreafioraldi** [comment]
Google don't use the instrumentation from llvm_mode but only afl-llvm-rt.o.c + their own instrumentation based on LLVM trace-pc. They link a single library to the target + a compatibility layer to use libFuzzer harnesses with AFL. This means that you will not able to use laf-intel, whitelist and all the other nice stuffs of AFL++ in LLVM mode.
We can't keep our codebase messed up with headers not in the include folder to have the shady scripts of Google working out of the box. You should adapt them to run AFL++ in the same way that you have to do to run other fuzzers that are not AFL and libFuzzer.

**Comment by egueler** [comment]
Thanks for the quick answer :-)
I was just going to write that it works, but that the laf-intel mode produces some errors, you beat me to it. It's good to know that it's not an afl++ issue, but a fuzzer-test-suite issue. I'll see what I can do to adjust fuzzer-test-suite for laf-intel support.
