### ISSUE TITLE
unicorn_mode: read(fd=197,...) = -1 EBADF (Bad file descriptor)

### ISSUE THREAD

**Issue by korniltsev** [vanhauser-thc/AFLplusplus#170]
Hi. I observer with strace  a strange behaviour - a failed read syscall on every fork. Errors sow-up one minute after fuzz start. Is this normal and expected?
```
/root/AFLplusplus/afl-fuzz -U -m none -t 120000 -i sample_inputs/  -o out_fuzz_tmp -- python simple_test_harness.py  @@
strace -fp 526
read(197, 0x7ffdf16522b0, 16) = -1 EBADF (Bad file descriptor)
... full log is in attachments
```
[strace.txt](https://github.com/vanhauser-thc/AFLplusplus/files/4042560/strace.txt)

**Comment by vanhauser-thc** [comment]
This is weird.

the important parts:
```
root@guest:~/AFLplusplus/unicorn_mode/samples/simple# strace -fp 526   <- this is afl-fuzz
[....]
pipe([120, 121])                        = 0
dup2(121, 197)                          = 197                <- what is this FD? its 198 and 199
close(121)                              = 0
clone(strace: Process 672 attached                   <- fork
[pid   526] close(197 <unfinished ...>                 <- parent closes fd
[...]
[pid   526] read(197, 0x7ffdf16522b0, 16) = -1 EBADF (Bad file descriptor) <- read on closed fd
```
so why is it reading on a closed fd?
and why fd 197?
I look at the code and there is nothing like that ...

**Comment by vanhauser-thc** [comment]
its unicorn_mode but it must be in afl-fuzz (or better, afl-forkserver.c)
@domenukk  @andreafioraldi @hexcoder-

**Comment by andreafioraldi** [comment]
197 is the translation blocks fd. It should be never be closed by the child, let me check if unicorn behaves like qemu

**Comment by vanhauser-thc** [comment]
its closed by afl-fuzz and then read on (if I interpret the strace correctly, I thought 526 is afl-fuzz)

**Comment by andreafioraldi** [comment]
No, 526 should be the parent unicorn process. It closes it (and this is correct) but then it read from it. I should read from 120 instead. I can't find this issue in the unicornafl code, but @domenukk seems to use TSL_FD for other stuffs than tb caching.

**Comment by domenukk** [comment]
Yes, if the struct matches `AFL_NEXT_TESTCASE_REQUEST` afl it's the next round in persistent mode, see https://github.com/vanhauser-thc/unicornafl/blob/ddef81a0a5c01b16115b1e3c3785a0e78a4235e4/afl-unicorn-cpu-inl.h#L330
I'll take a look at it tonight.

**Comment by domenukk** [comment]
All right, fixed this with the following unicornafl commit:
https://github.com/vanhauser-thc/unicornafl/commit/1b1e602654292ad31ef2e561427bc4e593e229e4

Specifically, unicornafl used the fd 197 and, at the same time, leaked one file descriptor. This meant the pipe() slowly made its way up to 197 and then, as it was always closed, reused this fd again. 
![image](https://user-images.githubusercontent.com/297744/72213478-f9bd9200-34ef-11ea-8c3d-89cad41c2753.png)

Again thanks for the report @korniltsev !
