### ISSUE TITLE
Set AFL_NO_X86 on other archs automatically

### ISSUE THREAD

**Issue by domenukk** [vanhauser-thc/AFLplusplus#172]
When compiling on ARM, a simple `make` will fail, as it will specifically try to generate X86 code. I don't see a reason not to always set `AFL_NO_X86` in this case.

**Comment by vanhauser-thc** [comment]
like with CPU = $(shell uname -m) etc. ?
that would be a good idea

**Comment by hexcoder-** [comment]
this should be done with 0eec6221554c260b2d93de73e88c2279c4479753. Feedback welcome.

**Comment by vanhauser-thc** [comment]
I think its done then:)
