### ISSUE TITLE
libdislocator: allocator may return misaligned pointers

### ISSUE THREAD

**Issue by i-ky** [vanhauser-thc/AFLplusplus#180]
Current [libdislocator documentation](https://github.com/vanhauser-thc/AFLplusplus/blob/master/libdislocator/README.dislocator.md) says:
> It allocates all buffers so that they are immediately adjacent to a subsequent PROT_NONE page, causing most off-by-one reads and writes to immediately segfault,

This is fine in most of the cases, e.g. when allocating an object or an array of objects, because size of the object is typically a multiple of its alignment requirement, and shifting allocated buffer to the right does not break the alignment of the beginning of the allocated buffer.

However, such allocation does not provide same guarantees, as one would expect from standard allocator, which always return a pointer, sufficiently aligned for any object.

One example, where this may cause issues is [flexible array member](https://en.wikipedia.org/wiki/Flexible_array_member):
```c
struct foo
{
    int bar;
    char baz[];
};
```
Calling code may allocate any number of bytes in addition to `sizeof` of the structure:
```c
struct foo *test = malloc(sizeof(foo) + 42);
```
When using libdislocator, any subsequent access to structure fields (`test.bar` in my example) will use misaligned pointer. [Here](https://github.com/curl/curl/issues/4540) is one of such issues in the wild.

I'm not saying it is necessarily a bug, since providing alignment guarantees according to standard will compromise libdislocator's abilities to catch off by one buffer overruns, but at least this nuance should be documented.

**Comment by andreafioraldi** [comment]
This should be configurable, like with the PerfectlyRightAlign flag of GwpASan.
I propose to introduce the AFL_ALIGNED_ALLOC env var. When it is defined, libdislocator will round the requested allocation size to the next multiple of `sizeof(void*)`.

**Comment by andreafioraldi** [comment]
Obviously this will reduce the ability of libdislocator to catch off by one bugs, but we can still insert canaries in the bytes added as padding to detect off-by-one oob write.

**Comment by i-ky** [comment]
Yes, configurable option can offer the best of both worlds.

**Comment by andreafioraldi** [comment]
Introduced in https://github.com/vanhauser-thc/AFLplusplus/commit/4384008f817f851e7fc329f24d803a5d829cb2db.
test.sh doesn't complain, it should be correct but a double check is always good @vanhauser-thc @hexcoder- @domenukk

**Comment by vanhauser-thc** [comment]
just looking at the patch and it looks ok, but dunno where else len is used and instead rlen would be right :)
maybe just adding a test case for test.sh for that new option?
