### ISSUE TITLE
move custom_mutators in experimantal

### ISSUE THREAD

**Issue by andreafioraldi** [vanhauser-thc/AFLplusplus#181]
The post library and persistent demo are in the experimental folder, I suggest to move also the custom mutator demo to that folder in order to be consistent and clean a bit the root folder.
Also, maybe we should rename the experimental folder to `examples` or something similar.

**Comment by andreafioraldi** [comment]
Same for python_mutators

**Comment by domenukk** [comment]
We could then also move `./unicorn_mode/samples` to be a subfolder of the `samples`/`examples`/`?`

**Comment by vanhauser-thc** [comment]
@andreafioraldi  - moving makes sense, examples sounds good
@domenukk - I would not move any *_mode files into examples/ but have each their own *_mode/example subfolder. I dont think anyone would think to find unicorn examples in a top folder called examples. but thats just me :)

**Comment by domenukk** [comment]
The idea would be that, no matter what you want to do, you find your answers in that folder.
Maybe even with a short readme.md describing what each individual example does

**Comment by andreafioraldi** [comment]
https://github.com/vanhauser-thc/AFLplusplus/commit/2fe7889912c9bb340f302a037585b7b1836ac94f

**Comment by andreafioraldi** [comment]
At this point, why not move test-instr.c from the root to test/ ?

**Comment by vanhauser-thc** [comment]
it would fit there - or to src/ ... it is so accustomed that it resides in the root though ... dunno.
other opinions?

**Comment by andreafioraldi** [comment]
We have too many files in the root dir, moving test-instr should not be an issue imo.
I also want to remove also the PATCHES symlink.
Another useless thing in root is Android.bp, IDK who placed it there but nobody is using it cause it is broken.
