### ISSUE TITLE
Support More Python 3 Versions

### ISSUE THREAD

**Issue by domenukk** [vanhauser-thc/AFLplusplus#182]
Arch now ships with Python 3.8 (released end of last year), the latest Ubuntu LTS (18.04) still uses Python 3.6. 
Right now, however, the Makefile fixes the required python version to 3.7, see https://github.com/vanhauser-thc/AFLplusplus/blob/c7167190a6abe9884787b0aae9e0728848971163/Makefile#L66
I suggest to, instead, fix it to python3 (any) and potentially parse `python3 --version` if we want to enforce a min version.

**Comment by vanhauser-thc** [comment]
as you proposed, python3 --version, python --version, python2 --version should be better
