### ISSUE TITLE
qemu persistent mode not working

### ISSUE THREAD

**Issue by vanhauser-thc** [vanhauser-thc/AFLplusplus#189]
This is weird. 5 laptops (not all the same Linux distro) compiling the same target. 3 this works, on 2 its not. this is from one of the not working one, binary attached.

```
# nm thumbnail | grep "T main"
0000000000004570 T main
# export AFL_QEMU_PERSISTENT_GPR=1
# export AFL_QEMU_PERSISTENT_ADDR=0x4000004570
# env | grep AFL
AFL_QEMU_PERSISTENT_ADDR=0x4000004570
AFL_SKIP_CPUFREQ=1
AFL_QEMU_PERSISTENT_GPR=1
# afl-fuzz -m none -i in/ -o out -Q -- ./thumbnail
afl-fuzz++2.60d based on afl by Michal Zalewski and a big online community
[...]
[*] Spinning up the fork server...
[+] All right - fork server is up.

[-] Unable to communicate with fork server. Some possible reasons:

    - You've run out of memory. Use -m to increase the the memory limit
      to something higher than 0.
    - The binary or one of the libraries it uses manages to create
      threads before the forkserver initializes.
    - The binary, at least in some circumstances, exits in a way that
      also kills the parent process - raise() could be the culprit.
    - If using persistent mode with QEMU, AFL_QEMU_PERSISTENT_ADDR is
      probably not valid (hint: add the base address in case of PIE)

If all else fails you can disable the fork server via AFL_NO_FORKSRV=1.

[-] PROGRAM ABORT : Unable to communicate with fork server
         Location : run_target(), src/afl-fuzz-run.c:200
```

[thumbnail.gz](https://github.com/vanhauser-thc/AFLplusplus/files/4172111/thumbnail.gz)

**Comment by andreafioraldi** [comment]
Can you attach a testcase and the libraries from ldd? The binary is not compatible with my OS

**Comment by andreafioraldi** [comment]
I mean a zip with all the libraries listed by ldd

**Comment by andreafioraldi** [comment]
Btw use `AFL_DEBUG_CHILD_OUTPUT=1 AFL_QEMU_DEBUG_MAPS=1` to check if 0x4000000000 is the actual base address

**Comment by vanhauser-thc** [comment]
It works if I use the address of _start, but not if it is the address of main.

Here is the output from DEBUG_MAPS showing its correct:
```
000000000-4000004000 r--p 00000000 fe:01 37365842                       /prg/tests/qemu/tiff-4.0.4/tools/thumbnail
4000004000-4000037000 r-xp 00004000 fe:01 37365842                       /prg/tests/qemu/tiff-4.0.4/tools/thumbnail
4000037000-4000061000 r--p 00037000 fe:01 37365842                       /prg/tests/qemu/tiff-4.0.4/tools/thumbnail
4000061000-4000062000 ---p 00000000 00:00 0 
4000062000-4000063000 r--p 00061000 fe:01 37365842                       /prg/tests/qemu/tiff-4.0.4/tools/thumbnail
4000063000-4000066000 rw-p 00062000 fe:01 37365842                       /prg/tests/qemu/tiff-4.0.4/tools/thumbnail
```

A zip with all libs is attached.
[full.zip](https://github.com/vanhauser-thc/AFLplusplus/files/4172231/full.zip)

**Comment by domenukk** [comment]
Just a stupid question, what happens if you just run thumbnail uninstrumented on that machine? Maybe it doesn't even reach `main`?

**Comment by vanhauser-thc** [comment]
here is another one, statically compiled, non-pie.
same issue. but here also the  _start address does not work.
[thumbnail.gz](https://github.com/vanhauser-thc/AFLplusplus/files/4172262/thumbnail.gz)

**Comment by vanhauser-thc** [comment]
@domenukk they work fine :)
and they work fine in qemu mode without persistent mode

**Comment by vanhauser-thc** [comment]
ah sorry, missing files.

rest of the libs:
[rest.zip](https://github.com/vanhauser-thc/AFLplusplus/files/4172821/rest.zip)

the static compile (wrong upload)


[static.zip](https://github.com/vanhauser-thc/AFLplusplus/files/4172886/static.zip)

**Comment by andreafioraldi** [comment]
The static binary runs fine with persistent qemu on my machine (there is 80% stability but works)

**Comment by vanhauser-thc** [comment]
what are your envs when successfully running it?

**Comment by andreafioraldi** [comment]
AFL_QEMU_PERSISTENT_ADDR=0x0000000000401760
AFL_QEMU_PERSISTENT_GPR=1

The binary is not PIE

**Comment by vanhauser-thc** [comment]
I wrote it is not pie :)
and weird: now it works. 
also the pie one works. 
I had the same parameter values for both.
WTF?
I will close this for now. as this not only happened on my laptop but also an other it could be its not my system that had an issue or my user error ... lets see if this pops up again.
