### ISSUE TITLE
Time-to-generate of fuzzed inputs

### ISSUE THREAD

**Issue by strongcourage** [vanhauser-thc/AFLplusplus#19]
Hi,

Do you think we should add the time-to-generate of fuzzed inputs to their names? It is quite useful when we need to compute the Time-to-Exposure (the length of the fuzzing
campaign until the first crashing input is generated) values to compare with other fuzzers. So the patch is very simple like this one: https://github.com/strongcourage/aflgo/commit/d73133e900f47542e9a725617d3df8edd6418476

Thanks,
Manh Dung

**Comment by hexcoder-** [comment]
I have no objections. It is useful, cheap and should not cause any incompabilities.

**Comment by vanhauser-thc** [comment]
I have no objections to this either. 

However its rather pointless IMHO.

If you compare fuzzers by which found a bug faster than that is not a good comparison. You want to measure speed, coverage and mutation effectiveness. And in the end you could measure which fuzzer found the *most* bugs in a specific time. But the *first* fuzzer to find a bug is really bad comparison IMHO

**Comment by strongcourage** [comment]
One application of fuzzing, especially directed fuzzing is crash reproduction (a.k.a, to reproduce known bugs). I think the most important and widely-used criteria is the Time-to-Exposure values. Note that simply counting number of inputs in crash folder is not correct since the PUT crashes due to different root cause or different kinds of bug.

In addition, some kinds of bugs like UAF don't crash program under test (PUT). Thus, in the bug triage process, we need to consider both crashing inputs and fuzzed inputs in the queue. 

My point is that this information is useful in the bug triage process. Thanks.

**Comment by vanhauser-thc** [comment]
I was just giving my opinion on it, that does not mean I wont put it in :)
I see it as a community repository, so if someone wants that and it does not have a negative impact it's added.

should it be on all queue/hang/crash files or only on hang and crash files?

**Comment by strongcourage** [comment]
We can add to all fuzzed inputs (crashes/, hang/, queue/). If you are OK, I will create a pull request. 

If anyone is interested in directed fuzzing like AFLGo (https://github.com/aflgo/aflgo), I am happy to contribute to this integration.

Thanks.

**Comment by vanhauser-thc** [comment]
@strongcourage - thanks for the pull request offer. I already have implemented a one-line solution which is now in the main branch

about aflgo - I will create a different issue for that for discussion.

**Comment by vanhauser-thc** [comment]
if you are satisfied with the solution just close this one - or comment if otherwise

**Comment by strongcourage** [comment]
Thanks.
