### ISSUE TITLE
Travis: git clone unicorafl timed out

### ISSUE THREAD

**Issue by andreafioraldi** [vanhauser-thc/AFLplusplus#190]
Sometimes Travis fails to git clone unicornafl, we shoud retry in case of failure like with wget in qemu mode. I left the bash sheningans to you.

**Comment by vanhauser-thc** [comment]
done.

btw - we should use a fixed llvm code-format version. newer versions have new options/defaults/... so using old and new versions result in different files.

**Comment by andreafioraldi** [comment]
I'm using clang-format 8. Should we use
```
`llvm-config-9 --bindir`/clang-format
```
instead? LLVM 9 is not installed on Ubuntu 18.04 LTS by default, however the 8 is in the repo.

**Comment by vanhauser-thc** [comment]
I dont think its important what is available in a distro but what we 4 have installed.
if you do not have 9 then lets set 8 as the default. hexcoder has all versions :)

@domenukk - do you have llvm 8?

**Comment by domenukk** [comment]
Both are fine by me. 20 LTS is around the corner anyway.
