### ISSUE TITLE
Add on-screen status message confirming AFL_USE_UBSAN is in use

### ISSUE THREAD

**Issue by geeknik** [vanhauser-thc/AFLplusplus#194]
Hi, thank you for improving AFL and thank you for adding the ability to use UBSan via AFL_USE_UBSAN=1. Could the code in afl-as.c be updated to show that we are using UBSAN?  

If we use AFL_USE_ASAN=1, we see this on screen:
`[+] Instrumented 449 locations (ASAN/MSAN mode, ratio 100%).`

If we use AFL_USE_UBSAN=1 today, we see this:
`[+] Instrumented 588 locations (non-hardened mode, ratio 100%).`

Thank you.

**Comment by hexcoder-** [comment]
Hi, AFL_USE_UBSAN currently is only supported in llvm_mode. So I am afraid combining AFL_USE_UBSAN with afl-gcc or afl-clang is a null operation.

Of course we could change that.

**Comment by geeknik** [comment]
Well, I only use llvm_mode for my operations, I've never once used afl-clang and it's been a few years since I used afl-gcc.

**Comment by andreafioraldi** [comment]
Don for llvm mode. As said by @hexcoder- , afl-as.c doesn't support sanitizers.

**Comment by geeknik** [comment]
Thank you for this. I'm curious what is happening now?

![Screenshot_2020-02-13_13-52-29](https://user-images.githubusercontent.com/466878/74472900-9fbb3e00-4e9a-11ea-8d24-2c88c4a798b0.png)

Also see stuff like this:
`Instrumented 2017 locations (]/UNSAN mode, ratio 100%).`
`[+] Instrumented 49681 locations (�"/UNSAN mode, ratio 100%).`

**Comment by geeknik** [comment]
Thank you for adding that. Could you explain what is happening in the status line now?

![Screenshot_2020-02-13_13-52-29](https://user-images.githubusercontent.com/466878/74473233-26701b00-4e9b-11ea-9b1f-3d6124539fb1.jpg)


Also seeing stuff like this:
`[+] Instrumented 49681 locations (�"/UNSAN mode, ratio 100%).`
`[+] Instrumented 2017 locations (]/UNSAN mode, ratio 100%).`

**Comment by hexcoder-** [comment]
@andreafioraldi: Sorry, but afl-gcc does support sanitizers.
I added the output similar to your change, but for afl-gcc, afl-clang-fast, afl-gcc-fast also.

**Comment by geeknik** [comment]
Look like commit 24dcc5 fixed the issue I was seeing in the status line. Thank you.

**Comment by hexcoder-** [comment]
ok, closing this.

**Comment by andreafioraldi** [comment]
> Thank you for adding that. Could you explain what is happening in the status line now?
> 
> ![Screenshot_2020-02-13_13-52-29](https://user-images.githubusercontent.com/466878/74473233-26701b00-4e9b-11ea-9b1f-3d6124539fb1.jpg)
> 
> Also seeing stuff like this:
> `[+] Instrumented 49681 locations (�"/UNSAN mode, ratio 100%).`
> `[+] Instrumented 2017 locations (]/UNSAN mode, ratio 100%).`

I simply pushed without testing lol (I'm not on my laptop) and I forgot the ={0} when intializing the array.
