### ISSUE TITLE
AFL_TMPDIR is being ignored

### ISSUE THREAD

**Issue by CaBeckmann** [vanhauser-thc/AFLplusplus#198]
If the environment variable AFL_TMPDIR is set the `.cur_input` file still gets written into the standard output directory. The problem is that `out_dir` gets used to build the path for `out_file` instead of `tmp_dir`.
Also the code to check if an input file already exists in TMP_DIR has two problems:
1) It does not check if `file_extension` is defined
2) I am pretty sure the parenthesis in the following line is at the wrong position and could lead to problems:
`char tmpfile[strlen(tmp_dir + 16)];`

**Comment by hexcoder-** [comment]
Hi, thanks. 
I agree with both problems, well spotted.
We need to investigate.

**Comment by vanhauser-thc** [comment]
@CaBeckmann can you please peer review the fix when hexcoder is done? Thanks!

**Comment by hexcoder-** [comment]
I am done now.

**Comment by CaBeckmann** [comment]
The change looks good and works for me. Thanks for the quick solution!
There was one thing I noticed while testing: When you use AFL_TMPDIR session resumption only works if you manually delete the `.cur_input` file. I am not sure if this is something that can be easily fixed though.

**Comment by vanhauser-thc** [comment]
@CaBeckmann that check is to ensure that not the same AFL_TMPDIR is used for more than one instance. In the case of a restart though we can conclude that everything is fine, so I disabled the check for resuming.

I am closing this now - reopen if you find any other issues :)
