### ISSUE TITLE
ROS build, refers to terminal

### ISSUE THREAD

**Issue by Kusoku** [vanhauser-thc/AFLplusplus#199]
Lately I've been looking into AFL and I've been trying to implement it for our project in ROS melodic under 64bit ubuntu, the build failed on compilation due to:

`CC=/usr/local/bin/afl-clang-fast CXX=/usr/local/bin/afl-clang-fast++ catkin build`

> CMake Error at /opt/ros/melodic/share/catkin/cmake/assert.cmake:17 (message): 
> Assertion failed: check for file existence, but filename (RT_LIBRARY-NOTFOUND) unset. 
> 
> Message: RT LibraryCall Stack (most recent call first): 
> /opt/ros/melodic/share/catkin/cmake/tools/rt.cmake:42 (assert_file_exists) 
> /opt/ros/melodic/share/catkin/cmake/all.cmake:147 (include) 
> /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:20 (include) CMakeLists.txt:4 (find_package)
> 
> CMakeLists.txt:4 find_package(catkin REQUIRED COMPONENTS roscpp)

As google/AFL didn't have this problem for either afl-gcc nor afl-clang I've looked around a bit and for the former one seems to start since removal of isatty(2): https://github.com/vanhauser-thc/AFLplusplus/commit/7a20cc2f58d2709a6b26c98bb6a931dfe5e186b6

For the latter it seems to occur since an earlier time, I've only verified that for release 2.57c it already didn't work.

Both methods compile the project if AFL_QUIET is used, but it would be nice to get the instrumentation information for components to which it was actually applied. For afl-gcc reverting the change works locally, for now I have no idea how to apply it correctly for afl-clang.

PS. Thanks a lot to all of you for your work with AFL

**Comment by vanhauser-thc** [comment]
@Kusoku I added the isatty check back into afl-as, please try again if it works now for you. also afl-clang-fast.

**Comment by Kusoku** [comment]
@vanhauser-thc yup, those changes solved the problem, now it builds completely with all afl-gcc/clang/clang-fast without problems 👍 

Thanks for your help.

**Comment by hexcoder-** [comment]
@Kusoku : since i originally removed the isatty check (in order to check, if gcc honors the option -B and really calls our instrumenting assembler wrapper afl-as), I would like to understand the real problem here.

Is true that your project uses its own preprocessor (roscpp)?
Was afl-as disturbing the build chain somehow with its output?

Thanks

**Comment by vanhauser-thc** [comment]
@hexcoder- FYI to have the output even if the output is redirected I added the AFL_DEBUG environment variable

basically:
```
  if ((isatty(2) && !getenv("AFL_QUIET")) || getenv("AFL_DEBUG")) {
       SAYF("...");
  else
       is_quiet = 1;
```

**Comment by hexcoder-** [comment]
@vanhauser-thc Thanks, I see, you also added `AFL_DEBUG` in the test in the `Makefile`. Fine!

**Comment by vanhauser-thc** [comment]
yeah otherwise the testcase in the Makefile would not work anymore ...

**Comment by Kusoku** [comment]
@hexcoder- from my understanding SAYF outputs data to the terminal which might've corrupted the [ROS process during initialization](http://wiki.ros.org/roscpp/Overview/Initialization%20and%20Shutdown):
> argc and argv
> ROS uses these to parse remapping arguments from the command line. It also modifies them so that they no longer contain any remapping arguments, so that if you call ros::init() before processing your command line you will not need to skip those arguments yourself.

While not exactly specified further [ros wiki](http://wiki.ros.org/CppStyleGuide#Console_output) mentions 2 more points:
>8. Avoid printf and friends (e.g., cout). Instead, use rosconsole for all your outputting needs.
>9. Avoid preprocessor macros whenever possible.

So there might be even more to it that just that initialization and your speculation towards preprocessor is correct. I've barely started with AFL and ROS so for now it's hard to say more from my side.
