### ISSUE TITLE
Error in `afl-fuzz': double free or corruption

### ISSUE THREAD

**Issue by ravi50041** [vanhauser-thc/AFLplusplus#200]
Error in `afl-fuzz': double free or corruption (!prev): 0x0000000000b203d0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f9b4ce877e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f9b4ce9037a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f9b4ce9453c]
afl-fuzz[0x404d5b]
afl-fuzz[0x413394]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f9b4ce30830]
afl-fuzz[0x4140c9]
======= Memory map: ========
00400000-0042b000 r-xp 00000000 fd:00 174001                             /usr/local/bin/afl-fuzz
0062a000-0062b000 r--p 0002a000 fd:00 174001                             /usr/local/bin/afl-fuzz
0062b000-0062c000 rw-p 0002b000 fd:00 174001                             /usr/local/bin/afl-fuzz
0062c000-00732000 rw-p 00000000 00:00 0
00a21000-00da5000 rw-p 00000000 00:00 0                                  [heap]
7f9b48000000-7f9b48021000 rw-p 00000000 00:00 0
7f9b48021000-7f9b4c000000 ---p 00000000 00:00 0
7f9b4c9f6000-7f9b4ca0c000 r-xp 00000000 fd:00 268                        /lib/x86_64-linux-gnu/libgcc_s.so.1
7f9b4ca0c000-7f9b4cc0b000 ---p 00016000 fd:00 268                        /lib/x86_64-linux-gnu/libgcc_s.so.1
7f9b4cc0b000-7f9b4cc0c000 rw-p 00015000 fd:00 268                        /lib/x86_64-linux-gnu/libgcc_s.so.1
7f9b4cc0c000-7f9b4cc0f000 r-xp 00000000 fd:00 496                        /lib/x86_64-linux-gnu/libdl-2.23.so
7f9b4cc0f000-7f9b4ce0e000 ---p 00003000 fd:00 496                        /lib/x86_64-linux-gnu/libdl-2.23.so
7f9b4ce0e000-7f9b4ce0f000 r--p 00002000 fd:00 496                        /lib/x86_64-linux-gnu/libdl-2.23.so
7f9b4ce0f000-7f9b4ce10000 rw-p 00003000 fd:00 496                        /lib/x86_64-linux-gnu/libdl-2.23.so
7f9b4ce10000-7f9b4cfd0000 r-xp 00000000 fd:00 1102                       /lib/x86_64-linux-gnu/libc-2.23.so
7f9b4cfd0000-7f9b4d1d0000 ---p 001c0000 fd:00 1102                       /lib/x86_64-linux-gnu/libc-2.23.so
7f9b4d1d0000-7f9b4d1d4000 r--p 001c0000 fd:00 1102                       /lib/x86_64-linux-gnu/libc-2.23.so
7f9b4d1d4000-7f9b4d1d6000 rw-p 001c4000 fd:00 1102                       /lib/x86_64-linux-gnu/libc-2.23.so
7f9b4d1d6000-7f9b4d1da000 rw-p 00000000 00:00 0
7f9b4d1da000-7f9b4d200000 r-xp 00000000 fd:00 754                        /lib/x86_64-linux-gnu/ld-2.23.so
7f9b4d3e1000-7f9b4d3f1000 rw-s 00000000 00:05 2818059                    /SYSV00000000 (deleted)
7f9b4d3f1000-7f9b4d3f5000 rw-p 00000000 00:00 0
7f9b4d3fd000-7f9b4d3fe000 rw-p 00000000 00:00 0
7f9b4d3fe000-7f9b4d3ff000 rw-p 00000000 00:2c 129                        /tmp/sdp_out/queue/id:000074,time:0,orig:id:000744,src:000740,op:havoc,rep:16,+cov
7f9b4d3ff000-7f9b4d400000 r--p 00025000 fd:00 754                        /lib/x86_64-linux-gnu/ld-2.23.so
7f9b4d400000-7f9b4d401000 rw-p 00026000 fd:00 754                        /lib/x86_64-linux-gnu/ld-2.23.so
7f9b4d401000-7f9b4d402000 rw-p 00000000 00:00 0
7fff30c34000-7fff30c55000 rw-p 00000000 00:00 0                          [stack]
7fff30c5e000-7fff30c61000 r--p 00000000 00:00 0                          [vvar]
7fff30c61000-7fff30c63000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted

**Comment by ravi50041** [comment]
version: afl-fuzz++2.60d
hostname: Ubuntu 16.04.6 LTS

**Comment by andreafioraldi** [comment]
Man, this is not a bug report. Please tell how to exactly reproduce the issue and give us also the output of AdressSanitizer (make ASAN_BUILD=1).

**Comment by vanhauser-thc** [comment]
I just freshly compiled with ASAN_BUILD=1 and letting it run, so far no crash. maybe @ravi50041 was unlucky for the git checkpoint point in time where there was a bug?
can you please retest with the current github state?
