### ISSUE TITLE
In libradamsa-test.c 

### ISSUE THREAD

**Issue by H4lo** [vanhauser-thc/AFLplusplus#204]
hello, In the following code, `init` function should be changed to `radamsa_init`:

https://github.com/vanhauser-thc/AFLplusplus/blob/ad79688c5fe096de6fcdb8fbeee2d1b70ad801e9/src/third_party/libradamsa/libradamsa-test.c#L60

**Comment by vanhauser-thc** [comment]
Correct, thanks!
