### ISSUE TITLE
Machine Learning for fuzzing (GSOC)

### ISSUE THREAD

**Issue by ashish493** [vanhauser-thc/AFLplusplus#207]
So after going through the ideas,
I'm thinking to go with project of creating the Fuzzer using ML (better than Neuzz xD).

At present, I'm going through the research papers about Fuzzers. Any more suggestions for resources are welcomed. :)

Is there any mentor suggested for this project? (as i really wanted some guidance for the type of fuzzer to be created).

P.S.- I do have experience in ML and Security.

**Comment by ashish493** [comment]
Also, are there any updates regarding FairFuzz??
And will there be any relation of it towards this project?

**Comment by vanhauser-thc** [comment]
@ashish493 

Fairfuzz will not be integrated into afl++ as it would require a lot of changes in a lot of areas. It can still be run in parallel in -S slave mode, so its not a big issue.

I think @domenukk would be the person in our group who has the most machine learning knowledge ... ?

Please note that you should register with GSoC first and familiarize yourself with afl++ and fuzzing, and handle an easier issue entry.

**Comment by andreafioraldi** [comment]
Refer #208 for GSoC

**Comment by hexcoder-** [comment]
Hi Andrea,

I don’t understand line 16 in qemu_mode unsigaction/Makefile.

Why is it necessary to exclude libunsigaction on arm architectures?

Thanks,
Heiko

**Comment by andreafioraldi** [comment]
Cause Wine is only x86 and x86_64 and we need unsigaction for Wine mode.

**Comment by hexcoder-** [comment]
I see, so it would not harm to activate it.

Von: Andrea Fioraldi <notifications@github.com>
Gesendet: Montag, 24. Februar 2020 13:57
An: vanhauser-thc/AFLplusplus <AFLplusplus@noreply.github.com>
Cc: hexcoder <heiko@hexco.de>; Comment <comment@noreply.github.com>
Betreff: Re: [vanhauser-thc/AFLplusplus] Machine Learning for fuzzing (GSOC) (#207)


Cause Wine is only x86 and x86_64 and we need unsigaction for Wine mode.

**Comment by vanhauser-thc** [comment]
@ashish493 can you please send an email to gsoc(at)aflplus(dot)plus - then I can send you an informational message about afl++ and GSOC 2020

**Comment by ashish493** [comment]
Yeah, sure..

**Comment by vanhauser-thc** [comment]
I will close this, please use issue #208 for GSoC as Andrea mentioned.
:)
