### ISSUE TITLE
error while running 32bit assembly?

### ISSUE THREAD

**Issue by aar0nge** [vanhauser-thc/AFLplusplus#210]
while running a simple "push ..." instruction, I get this problem:
![image](https://user-images.githubusercontent.com/20163299/75257081-67fbb100-581f-11ea-86db-20b3b7d1546c.png)
the current esp is 0xbffff0a0, but the "push" instruction's write address has become 0xf09c, and I get an invalid write.
I have mapped memory in 0xbfff000 correctly and I don't want to change it to 0xf000, has anyone met this kind of problems? How should I get it right? 

I run this code by running:
```
from unicornafl import *
...
uc = Uc(UC_ARCH_X86, UC_MODE_32)
uc.afl_fuzz(......
```
strangely while I changed it to:
`uc = Uc(UC_ARCH_X86, UC_MODE_64)`, it can run the "push" instruction correctly, but it's a 32bit binary so there are other errors later.
And when I run a 64bit binary there is no problem in running the "push" instruction.
The higher 2 bytes of esp has become 0, I guess maybe it's a bug in unicornafl? Since when I just use unicorn it's ok. 
Could someone please help me?

**Comment by hexcoder-** [comment]
I do not see any relation to AFL++.

**Comment by aar0nge** [comment]
> I do not see any relation to AFL++.

I run it by unicornafl, is here the right place?

**Comment by hexcoder-** [comment]
Aha, yes it is.

But a good bug report provides as much information as possible for developers to reproduce the issue. For example, platform and operating system being used, command line used, complete screenshots, and so on.

@domenukk This is probably your area.

**Comment by domenukk** [comment]
@aar0nge also, can you try if the bug exists in vanilla unicorn (https://github.com/unicorn-engine/unicorn) ? If so, this would be the better place for a bug report :)

**Comment by aar0nge** [comment]
Thanks for your advice, there are some other context and environment setup (specifically: [unicorefuzz](https://github.com/fgsect/unicorefuzz)), I am trying to make it simpler to reproduce. Let me debug for a while...
(It's ubuntu 18.04, unicorn 1.0.2 btw)

**Comment by aar0nge** [comment]
So... I can't not reproduce it by unicornafl... looks like it's a problem in unicorefuzz, maybe avatar2 or something. Then here is not the place, I would close this now.
