### ISSUE TITLE
unknown regression in v2.61c

### ISSUE THREAD

**Issue by wideglide** [vanhauser-thc/AFLplusplus#214]
I'm experiencing a significant (?) regression when using v2.61c versus v2.60c and I can't isolate what might have changed to cause this result.

I'm running tests on the LAVA / Rode0day corpora.

Both experiments were identical except for rebuilding my docker container with either
- `git clone -b 2.60c` or
- `git clone -b 2.61c`

The coverage exposed is roughly the same, but v2.61c doesn't find any crashes/bugs where v2.60c finds bugs within the first minute and over 200 crashes total??

I'm running in slave/havoc only mode with a dictionary generated from objdump as described here https://moyix.blogspot.com/2016/07/fuzzing-with-afl-is-an-art.html.  So, shallow bugs in LAVA targets should be easily found by AFL fuzzing with the dictionary.
I'm also running the generated testcases under a second process which logs coverage and checks for bugs.  So, I don't believe the problem is that AFL is not catching faulting inputs, I think somehow it is failing to generate crashing inputs?

Here's from v2.60c
![image](https://user-images.githubusercontent.com/558033/75450796-750ec200-593d-11ea-8785-cafe011103df.png)

Here's v2.61c
![image](https://user-images.githubusercontent.com/558033/75450856-8eb00980-593d-11ea-83d4-d6c52db49140.png)

**Comment by andreafioraldi** [comment]
Hi, are you using qemu or llvm?

**Comment by wideglide** [comment]
llvm 9.0, compiled with afl-clang-fast

**Comment by andreafioraldi** [comment]
>  So, I don't believe the problem is that AFL is not catching faulting inputs, I think somehow it is failing to generate crashing inputs?

This is unlikely. Try to put a crashing input in the initial folder. If a crash is detected during the dry run of the initial corpus, AFL++ aborts. If it doesn't abort, the problem is that the fuzzer doesn't detect crashes.

**Comment by wideglide** [comment]
I ran another experiment, this time rebuilding from master instead of `2.61c` and it was able to find one crash after 6 minutes, but then no more.  So, I don't think it is the ability to detect crashes, but I can try your suggestion, it would validate my hypothesis.
here's the log from that run: https://test.fuzz.tr0gd0r.com/stats/show/2504

I've diff'd the afl-fuzz source between 2.60c...master and I don't see anything that would cause this behavior.  But after several attempts, the behavior is repeatable and significantly different. In the image below, crashes <= 2 is where 2.61c/master was used and crashes >80 was either stock AFL or AFL++ 2.60c.  I also tried an experiment in qemu mode, with an un-instrumented version of the same binary, and the results were the same (no crashes).

![image](https://user-images.githubusercontent.com/558033/75461765-3d117a00-5951-11ea-89ab-d9410d6917f3.png)

**Comment by andreafioraldi** [comment]
>  I also tried an experiment in qemu mode, with an un-instrumented version of the same binary, and the results were the same (no crashes).

At least we know that is not an llvm mode issue. Try dry run and let me know.

**Comment by wideglide** [comment]
dry run works
```
[-] PROGRAM ABORT : Test case 'id:000000,time:0,orig:crash003719' results in a crash
         Location : perform_dry_run(), src/afl-fuzz-init.c:657
```

**Comment by vanhauser-thc** [comment]
A lot of things in afl are random, which input is selected, what bytes are changed, etc.
if you want to compare the two versions, then run them with the same command line options and add  -s 123   <- this fixes the random number initialization so the randomness is the same.

also - what is your full command line? I see no deterministic mutation in the screen shot.

**Comment by wideglide** [comment]
There's certainly a lot of randomness in AFL, but 5 experiments that produce > 80 crashes and 5 experiments that produce < 2 crashes is a good indicator that randomness is not at play which the only variable that changes is the commit hash that I use to build AFL++.

Here's the full command line:
```
/usr/local/bin/afl-fuzz -i inputs -o outputs -m 4096 -t 2000 -x dict/consts.txt -S pcreB000 -- ./lava-afl-cf/bin/pcre2grep -f @@ ./inputs/haystack
```

I'm starting a search for the code change, and just ran a test on commit c7167190a6abe9884787b0aae9e0728848971163 (Feb 01) which is still working, so it appears the change was after that.

**Comment by andreafioraldi** [comment]
Try with https://github.com/vanhauser-thc/AFLplusplus/commit/54bbddec602feef0bd4e3bdc066c50779825d178.
If it is broken, may be a issue due to cmplog. If so, we have to do a binary search for the broken commit :(

**Comment by wideglide** [comment]
I tried b133fa3b6e18d46e53fddba10f09097c9bef6868 which still works, so its something after 15 Feb

**Comment by andreafioraldi** [comment]
There should not be code that touch the mutator or the crash handler modified after 15 feb.
This is strange. Test https://github.com/vanhauser-thc/AFLplusplus/commit/249cd2c7669f9dc9f49e96756b6683744213ee08

**Comment by vanhauser-thc** [comment]
Please do all comparisons tests with a fixed same -s value so that there are false positives/negatives because of randomness. 

Thank you for your effort!

**Comment by wideglide** [comment]
It appears it was actually introduced between b133a3 and 3beee6da772f88f1bd7987b4b2e7c56a53ec3270  (15-18 Feb)?  I'm double checking.

**Comment by wideglide** [comment]
ok, It was something introduced on the 17th, but I'm having trouble isolating it because `afl-fuzz` crashes within 10 seconds on many of those commits.

"good" means it still finds crashes

b133fa3b6e18d46e53fddba10f09097c9bef6868 16th -- good
4bca8af499a6ecbd2c6111f4820b66c2ba4710b5 16th -- good
8acd503526eda9d8c87374d8cf570aeac54ced73 16th -- good
d41f4130168629ec01f420b79fce42f4f0c11961 16th -- good
220804714bb4cc8722940fd4fe6a0604901dfd2a 17th -- good, double free
df55fb1f14050a5223229d5df9d0a76ba7b23521 17th -- double free
3e20edf10e5129e990c295b86e14d896c4a3ca48 17th -- corrupted
ac08a38db993ef60937ae9c304dd1d418ddf5cb1 18th -- no bugs, double free in fuzz_one_original
a32c671ac9606b6e1778b91d1bf789df1e52269b 18th -- no bugs

```
*** Error in `/usr/local/bin/afl-fuzz': double free or corruption (!prev): 0x0000000000824c20 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7ffff7a847e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7ffff7a8d37a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7ffff7a9153c]
/usr/local/bin/afl-fuzz(fuzz_one_original+0x10f1)[0x410b71]
/usr/local/bin/afl-fuzz(fuzz_one+0x35)[0x42ff35]
/usr/local/bin/afl-fuzz(main+0x1f07)[0x408a37]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7ffff7a2d830]
/usr/local/bin/afl-fuzz(_start+0x29)[0x409259]
======= Memory map: ========
```

```
*** Error in `/usr/local/i386/afl-fuzz': corrupted size vs. prev_size: 0x0000000001ef1820 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f94c08f47e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x82aec)[0x7f94c08ffaec]
/lib/x86_64-linux-gnu/libc.so.6(__libc_malloc+0x54)[0x7f94c0901184]
/usr/local/i386/afl-fuzz[0x4312e6]
/usr/local/i386/afl-fuzz(fuzz_one_original+0x1537)[0x411147]
/usr/local/i386/afl-fuzz(fuzz_one+0x35)[0x430065]
/usr/local/i386/afl-fuzz(main+0x2144)[0x408c74]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f94c089d830]
/usr/local/i386/afl-fuzz(_start+0x29)[0x409289]
======= Memory map: ========
```

**Comment by wideglide** [comment]
It's the changes to `alloc-inl.h`.  I just used the version from https://github.com/AFL with master and everything works fine.

**Comment by andreafioraldi** [comment]
Thank you man for the great effort, I'll backport it from AFL as a workaround and meanwhile, I'll work for a better solution.

**Comment by andreafioraldi** [comment]
Now you can use master

**Comment by andreafioraldi** [comment]
@vanhauser-thc we need a hotfix release when I'll finish with this.

**Comment by vanhauser-thc** [comment]
Write here when you are done

**Comment by vanhauser-thc** [comment]
@wideglide can you please try the new github state? I made some changes to alloc-inl.h and it works fine for me (15 crashes in 8 minutes for my test target tiff-4.0.4)

If this works for you I make a new release with this version, if this also produces a problem then I revert to the original one and make with that a new release.

**Comment by wideglide** [comment]
the most recent commit caused an error for me:
```
[*] Testing the CC wrapper and instrumentation output...
./afl-showmap -m none -q -o .test-instr0 ./test-instr < /dev/null

[-]  SYSTEM ERROR : shmat() failed
    Stop location : setup_shm(), src/afl-sharedmem.c:195
       OS message : No such file or directory
```

**Comment by vanhauser-thc** [comment]
have you done a "make clean" first?

**Comment by vanhauser-thc** [comment]
sorry my mistake!

**Comment by vanhauser-thc** [comment]
fix is in, now you can test. sorry. I am very tired ...

**Comment by wideglide** [comment]
built from f526bb2ecb6dbbf6b155f12f6e8e12596cd1b84c which works!
the changes you made to `alloc-inl.h` seem to be fine.

**Comment by vanhauser-thc** [comment]
so all the crashes that should be there are being found now?

**Comment by wideglide** [comment]
yes, the differences I was seeing were immediately obvious.
I just was able to build from master as well.

**Comment by vanhauser-thc** [comment]
perfect then I will do the new release now and then fall into my bed :)
thanks a lot for your great effort!!
