### ISSUE TITLE
build failure in travis

### ISSUE THREAD

**Issue by wideglide** [vanhauser-thc/AFLplusplus#218]
Seems like this should cause travis-CI to report a failure instead of success?

```
afl-common.o: In function `get_afl_env':
/home/travis/build/vanhauser-thc/AFLplusplus/llvm_mode/../src/afl-common.c:(.text+0xef6): undefined reference to `be_quiet'
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by emocat** [comment]
I've met this problem too. One simple way is just to commet out code below at 323, src/afl-commen.c:
```c
if ((val = getenv(env)) != NULL)
    //if (!be_quiet)
    OKF("Loaded environment variable %s with value %s\n", env, val);
```

**Comment by andreafioraldi** [comment]
`[-] llvm_mode not compiled, cannot test` @vanhauser-thc we should add an env var that tell test.sh to about when running on travis
