### ISSUE TITLE
CompareCoverage in QEMU mode?

### ISSUE THREAD

**Issue by andreafioraldi** [vanhauser-thc/AFLplusplus#22]
We support laf-intel in LLVM mode, why not support an equivalent instrumentation in QEMU mode?
I'm experimenting a bit with the x86 target and I will create a branch for this.
The idea is to not touch the fuzzer but work only in QEMU.
The implementation will be different from honggfuzz that uses a different map for CompareCoverage, my idea is to put all in the AFL map.
This can create problems with large targets and the user may need to enlarge MAP_SIZE but this is also true for laf-intel.
Obviously this mode is off by default and can be enabled setting an env variable (I called it AFL_QEMU_COMPCOV in my experiment of this evening).
Let me know your opinion.

**Comment by andreafioraldi** [comment]
If I'm correct this will make afl++ the first public fuzzer to support such instrumentation in binary-only mode.

**Comment by vanhauser-thc** [comment]
@andreafioraldi that sounds very cool ... didnt think that would actually be possible :)

**Comment by andreafioraldi** [comment]
I uploaded the code in the qemu-compcov branch. The main changes are in https://github.com/vanhauser-thc/AFLplusplus/blob/qemu-compcov/qemu_mode/patches/i386-translate.diff and https://github.com/vanhauser-thc/AFLplusplus/blob/qemu-compcov/qemu_mode/patches/afl-qemu-cpu-translate-inl.h.
I don't know if this is really effective at the moment.

**Comment by andreafioraldi** [comment]
For the coverage of mem/strcmp and related functions I was thinking about creating an external library that have to be loaded with LD_PRELOAD, it's only and idea I will implement it when I will have time.

**Comment by andreafioraldi** [comment]
Simple tests are promising.
Fuzzing LAVA-M who for 50 minutes afl++ can discover ~30 unique crashes with compcov qemu vs. 2 with normal qemu. The majority of the crashes were discovered in the last 10 minutes cause the progress of the cmp is horizontal and so I think that the crashes will double when fuzzing for an hour (my train arrived and so I had to shutdown the laptop).

**Comment by andreafioraldi** [comment]
Note that the queue grows a lot (~3k vs 120) but  LAVA-M is a patological case for cmp bypassing, test on real targets is needed.

**Comment by vanhauser-thc** [comment]
@andreafioraldi that sounds very good already!

I am busy today with testing fairfuzz and trying an aggressive trimming option in afl-fuzz.

what would a good target be? as its string compares I guess something like libxml2 I guess?

**Comment by andreafioraldi** [comment]
String compare are not supported atm but I will implement the library asap. This evening I will try to fuzz djpeg, it has a lot of cmp/sub instructions.

**Comment by andreafioraldi** [comment]
Results of ~7 hour and half of fuzzing libpng.

![plot_bb](https://user-images.githubusercontent.com/16168186/61570731-dc52c280-aa8e-11e9-8e54-51e1bce917ae.png)

**Comment by vanhauser-thc** [comment]
that looks good!

I am running this now on libtiff (as libxml2 crashes qemu - see issue #24) for 2 hours.

paths discovered do not tell you anything - see the discussion in issue #18. what you want to compare is coverage and this can be done with afl-cov. e.g. MOpt has fantastic numbers of discovered paths compared against anything, but when checked against the coverage its bad. (its a good mode but has to be used differently)

I will post my results later, so far the library seems to be effective

**Comment by andreafioraldi** [comment]
The first plot are basic block/time, the second the number of items in queue (what in labeled "paths" in the status screen). To measure performance of course bbs/time are needed but when I want monitor also if there is "queue explosion". The second graph is not for performance measurement.

**Comment by vanhauser-thc** [comment]
what happens if you do to many things in parallel ... I tested libtiff but actually didnt check if there is actually something in there that would benefit from your implementation. because after 2h of fuzzing - same coverage.
so I compile with llvm_mode and laf-intel .... and it reported nothing for laf-intel to do ;)

testing unrar now, there are lots of memcmp etc in there

**Comment by andreafioraldi** [comment]
Yes it is normal, as described in the laf-intel blogpost (https://lafintel.wordpress.com/) there are targets that does not benefits from the technique and some other that have less performance. In addition, 2h may not be enough cause in some targets the advantages are in the long term (see their evaluation).
In general, when you have a closed binary with many comparison that depends directly on the input (the chunk names "gAMA" "iCCP" etc. in PNG) without a dictionary using laf-intel/compcov is a good idea. Of course, by default, this will be disabled and in fact I disagree with your choice (in TODO for 2.53d) to enable laf-intel by default in LLVM mode.

**Comment by andreafioraldi** [comment]
Regards parallel fuzzing a good idea is to enable CompareCoverage only in the master.

**Comment by vanhauser-thc** [comment]
I added an example to test into the lib... directory. plus I added a debug routine (which kinda works but also makes it super slow, so -t 1000000 is kinda needed ;) with AFL_QEMU_COMPCOV_DEBUG=1

**Comment by andreafioraldi** [comment]
Maybe it's time to merge?

**Comment by vanhauser-thc** [comment]
Your decision :)

**Comment by andreafioraldi** [comment]
Done after an improvement to libcompcov
