### ISSUE TITLE
how to build afl-clang with different version

### ISSUE THREAD

**Issue by Hanseltu** [vanhauser-thc/AFLplusplus#222]
Hi, I want to know how to build afl++ with a different clang version.

Now, I get clang version 3.8.0 using `afl-clang --version`, and the output is 

```
afl-cc++2.60d by Michal Zalewski
[!] NOTE: afl-gcc is deprecated, llvm_mode is much faster and has more options
clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
I used `make CC=clang-6.0` to build, but it didn't work for me.  So how to build afl++ with clang version 6.0 or higher?

Thanks.

**Comment by vanhauser-thc** [comment]
If you look at llvm_mode/README.md you will find that you need to set LLVM_CONFIG pointing to the llvm-config-6.0 or whatever version to achieve this ... ;)
