### ISSUE TITLE
test.sh does not aborts when there are errors

### ISSUE THREAD

**Issue by andreafioraldi** [vanhauser-thc/AFLplusplus#224]
See this https://travis-ci.com/vanhauser-thc/AFLplusplus/jobs/294050859
There is a Null Ptr Deref in the fuzzer reported by ASan and Travis says that all tests are fine.

**Comment by vanhauser-thc** [comment]
ah damn. yes that was something I tried to workaround the arm64 travis issue.
now it reports correctly again. sorry

**Comment by maribu** [comment]
At least in 5.00c and 5.01c the issue popped up again: The exit code of the tests is "success" even when there have been failures 😦

**Comment by vanhauser-thc** [comment]
Doesn’t for me, just fixed a test issue on the weekend. Maybe a test is missing setting the error but then tell me which one you noticed

**Comment by maribu** [comment]
Specifically, if building the docker image during the test fails, the test still reports a success.
