### ISSUE TITLE
build_qemu_support.sh for i386 fails

### ISSUE THREAD

**Issue by fuzzah** [vanhauser-thc/AFLplusplus#227]
Hi.
build_qemu_support.sh fails when compiling for i386 support:
```
$ env CPU_TARGET=i386 ./build_qemu_support.sh
```

Relevant part of compile log:
```
  CC      i386-linux-user/trace/control-target.o
  CC      i386-linux-user/gdbstub-xml.o
  CC      i386-linux-user/trace/generated-helpers.o
  LINK    i386-linux-user/qemu-i386
/usr/bin/ld: linux-user/syscall.o: in function `do_syscall1':
/home/user/git/AFLplusplus/qemu_mode/qemu-3.1.1/linux-user/syscall.c:7334: undefined reference to `stime'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:199: qemu-i386] Error 1
make: *** [Makefile:483: subdir-i386-linux-user] Error 2
```

Some info:
```
commit 90409f383a728fdcf4d66ffc607f1e3eb70b9203 (HEAD -> master, origin/master, origin/HEAD)
Author: van Hauser <vh@thc.org>
Date:   Thu Mar 5 11:36:37 2020 +0100

    added AFL_QUIET - be_quiet to afl-showmap and small changes to test.sh
```

```
$ uname -a
Linux localhost 5.5.7-arch1-1 #1 SMP PREEMPT Sat, 29 Feb 2020 19:06:02 +0000 x86_64 GNU/Linux
```

**Comment by andreafioraldi** [comment]
stime(2) is a libc function, it seems to be deprecated after GLIBC 2.31 (that no system have, apart Arch, that is always a PITA).
Here the fix for the same issue in busybox
https://git.busybox.net/busybox/patch/?id=d3539be8f27b8cbfdfee460fe08299158f08bcd9
I'll backport it from QEMU 4 when I'll have some free time, meanwhile you can simply use docker and fuzz on Ubuntu.

**Comment by andreafioraldi** [comment]
Code to backport (reference for myself) https://github.com/qemu/qemu/blob/master/linux-user/syscall.c#L7838

**Comment by andreafioraldi** [comment]
Ok the patch is super simple, wait a minute I'll do it now.

**Comment by andreafioraldi** [comment]
Pull & try it please @fuzzah

**Comment by heiyu121** [comment]
>Ok the patch is super simple, wait a minute I'll do it now.



> Ok the patch is super simple, wait a minute I'll do it now.
Hello, I also have the same problem, may I ask how to solve it specifically? Where is patch? I haven't found it yet

**Comment by Licae** [comment]
> Ok the patch is super simple, wait a minute I'll do it now.

Hello, I also have the same problem, may I ask how to solve it specifically? Where is patch? I haven't found it yet
