### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by localh0rs7** [vanhauser-thc/AFLplusplus#229]
I do not understand how the mutator modules are getting parsed from the commandline.
If I execute...  

`AFL_PYTHON_MODULE="pathto/module.py"` PYTHONPATH=. afl-fuzz`
AFL says:

> ModuleNotFoundError: No module named '"pathto/module'
Failed to load ""pathto/module.py"
> [-] PROGRAM ABORT : Failed to initialize Python module

I also tried to link /usr/bin/python3.7 in the AFL_PYTHON_MODULE variable.

Best,
Christian

**Comment by localh0rs7** [comment]
thanks for the hint, got this.
there is also a flag mentioned: 
`AFL_PYTHON_ONLY`

I tried to set this to "1" or TRUE but get the following warning:

`[!] WARNING: Mistyped AFL environment variable: AFL_PYTHON_ONLY=`

What is the value of the env variable supposed to be?
There is no specification about this as far as i saw.

**Comment by h1994st** [comment]
@localh0rs7  In a recent commit, `AFL_PYTHON_ONLY` has been removed in the master branch. This is why you saw the warning. If you want to only use the custom mutator, try to set `AFL_CUSTOM_MUTATOR_ONLY`. (See [docs/custom_mutators.md](https://github.com/vanhauser-thc/AFLplusplus/blob/master/docs/custom_mutators.md))

**Comment by vanhauser-thc** [comment]
It was still in the custom_mutators.md - removed it.
@localh0rs7 - thanks for reporting!
