### ISSUE TITLE
MOpt havoc doesn't appears in UI

### ISSUE THREAD

**Issue by andreafioraldi** [vanhauser-thc/AFLplusplus#23]
I'm trying QEMU CompCov in combination with MOpt and I notoced that the results of MOpt havoc are not shown in the UI

![Screenshot at 2019-07-19 09-22-39](https://user-images.githubusercontent.com/16168186/61517194-f8ab1c80-aa06-11e9-8351-8818c4145cc0.png)

As you can see only the information about trim are present.

**Comment by vanhauser-thc** [comment]
did you run it with -L0?
for anything X > 0 it means it runs normal afl and only after X minutes of no new paths found it activates MOpt.

but even if running in MOpt it uses some of the original afl mutators. when it's special mutators are running you an see it in the "now tryiing" row.

**Comment by vanhauser-thc** [comment]
btw - can you send me an email at mh@mh-sec.de? to discuss planning aside from issues :)

Plan is to go into feature freeze on Sunday and do a release between Thursday and Sunday next week.

**Comment by vanhauser-thc** [comment]
@andreafioraldi no creating an issue is the right thing.

the email is for overall afl++ planning and strategy as I dont have your email address :)

About the issue: I dont understand what you think is going wrong. is it that trim 4/4 should never happen in MOpt?

**Comment by andreafioraldi** [comment]
The issue is that this stuff https://github.com/vanhauser-thc/AFLplusplus/blob/866e22355c4bb00abe6ee43c7ff2231e93b15005/afl-fuzz.c#L7107 is not present in the MOpt fuzz routine. Without updating stage_finds and stage_cycles the "fuzzing strategy yields" fields in the UI are always 0.

**Comment by vanhauser-thc** [comment]
ah ok. can you fix it? I am in-deep in rare_trim at the moment :)

**Comment by andreafioraldi** [comment]
Of course but not today, tomorrow morning i can.

**Comment by vanhauser-thc** [comment]
no clue what that fix did :D - but thank you for taking care of it :)
