### ISSUE TITLE
Unexpected Behavior in afl-cmin When Exiting With Ctrl+C

### ISSUE THREAD

**Issue by domenukk** [vanhauser-thc/AFLplusplus#230]
Hitting `ctrl+c` cancels execution of `afl-showmap`, yet the awk script continues to process the output files:
```bash
corpus minimization tool for afl++ (awk version)

[*] Testing the target binary...
[+] OK, 760 tuples recorded.
[*] Obtaining traces for 319 input files in 'errc_fuzz_hangs/'.
    Processing 319 files (forkserver mode)...
[+] All right - fork server is up.


^C
+++ afl-showmap folder mode aborted by user +++

[-]  SYSTEM ERROR : Unable to create 'cminimized_hangs/.traces'
    Stop location : write_to_file(), src/afl-showmap.c:258
       OS message : File exists
[*] Processing traces for input files in 'errc_fuzz_hangs/'.
    Processing file 319/319
    Processing tuple 8300/8300 with count 64...
[+] Found 8300 unique tuples across 319 files.
[+] Narrowed down to 60 files, saved in 'cminimized_hangs'.
```

Btw. in my current build (a few days old) the `afl-cmin` is awfully quiet after the forkserver spun up. 
In contrast, `afl-cmin.bash` informs about the current file progress.

**Comment by hexcoder-** [comment]
ok, Ctrl-C should terminate afl-cmin, but currently only terminates its child afl-showmap.
I will investigate how to change that.
@van-hauser: What exit code does afl-showmap set, when Ctrl-C'ed?

Regarding verbose progress while producing trace files:
That would have to be added in afl-showmap (-i dir mode).

**Comment by hexcoder-** [comment]
I found a way 0d4f2da to detect a terminated child under GNU awk (Linux), which seems to be the only
awk implementation, where signals are (correctly) ignored during system(): 

```
  if (!stdin_file) {
    print "    Processing "in_count" files (forkserver mode)..."
    retval = system( "AFL_CMIN_ALLOW_ANY=1 \""showmap"\" -m "mem_limit" -t "timeout" -o \""trace_dir"\" -Z "extra_par" -i \""in_dir"\" -- \""target_bin"\" "prog_args_string)
  } else {
    print "    Processing "in_count" files (forkserver mode)..."
    retval = system( "AFL_CMIN_ALLOW_ANY=1 \""showmap"\" -m "mem_limit" -t "timeout" -o \""trace_dir"\" -Z "extra_par" -i \""in_dir"\" -- \""target_bin"\" "prog_args_string" </dev/null")
  }

  if (retval > 127) {
    retval = retval - 128
    if (retval > 127) {
      retval = retval - 128
    }
    printf "[!]Signal %d received, terminating...\n", retval
    exit 1
  }
```
Under nawk (*BSD) and mawk (Raspbian) system() does not switch to ignoring the signals (which it should!), so this problem with not terminating is not there anyway.

**Comment by hexcoder-** [comment]
@vanhauser-thc : Regarding 
```
^C
+++ afl-showmap folder mode aborted by user +++

[-]  SYSTEM ERROR : Unable to create 'cminimized_hangs/.traces'
    Stop location : write_to_file(), src/afl-showmap.c:258
       OS message : File exists
```
Line 354 in afl-showmap.c looks wrong to me.
If it is only reached in folder mode (as the message suggests) I would delete it
(in folder mode `out_file` only contains the output directory path, not a file path).

**Comment by vanhauser-thc** [comment]
@hexcoder- I think this is fixed now?

**Comment by hexcoder-** [comment]
@vanhauser-thc: Please check afl-showmap.c (now at line 334) first. See my comment above.

**Comment by vanhauser-thc** [comment]
it is in the forkserver handler so yes, it is only folder mode, and yes then out_file is actually an output directory.
It would however say that in this case afl-cmin could wipe the directory as the caller and we remove that close() from afl-showmap?

**Comment by hexcoder-** [comment]
Yes, ok, I will remove the line in afl-afl-showmap.c, add clearing the output directory to afl-cmin when Ctrl-C'ed and then close this issue.
