### ISSUE TITLE
AFL_QUIET ignored in some parts of LLVM mode

### ISSUE THREAD

**Issue by andreafioraldi** [vanhauser-thc/AFLplusplus#236]
There is some code in LLVM mode that prints additional info on stderr (e.g. laf-intel) also when AFL_QUIET=1.

**Comment by vanhauser-thc** [comment]
I hope I got them all in dcf7d85

**Comment by vanhauser-thc** [comment]
no there are passes which use errs() ... sigh

**Comment by vanhauser-thc** [comment]
OK got them now all I think. several were in your code ;)

**Comment by vanhauser-thc** [comment]
df74ede

**Comment by andreafioraldi** [comment]
> OK got them now all I think. several were in your code ;)

yes I copy-pasted from laf passes
