### ISSUE TITLE
fixing "no globals"

### ISSUE THREAD

**Issue by vanhauser-thc** [vanhauser-thc/AFLplusplus#244]
@domenukk I am out of time for today for fixing.

afl-tmin and afl-showmap do not work if the input is sent via stdin (but fine in file/@@ mode).

**Comment by domenukk** [comment]
Worked on it with commit 1136e88.
Keeping this issue open until travis finishes

**Comment by domenukk** [comment]
Leaks are gone, albeit afl-cmin and afl-tmin still seem broken. 
I sadly don't have the time to fix it right now.

**Comment by vanhauser-thc** [comment]
The issue was that neither afl-tmin nor afl-showmap were initializing their fsrv structure like afl_init() is doing in afl-fuzz.
So what I implemented is that in afl-forkserver.c fsrv_init() checks if use_stdin is 1 (which is the default), and if not then set the necessary defaults.

afl-tmin and afl-showmap work now and test.sh runs through clean with ASAN enabled

I think we should keep the issue open until we are sure there are no other bugs.

**Comment by vanhauser-thc** [comment]
I did a speed comparison and it might be a little bit slower, but it is so minimal (maybe < 0.5%) it is not important IMHO.

What is however a big issue is that the results are not uniform.

What I mean is: with "old" afl-fuzz if we set a fixed random number initialization (e.g. `-s 123`) then the results would be uniform meaning the path discovered etc would happen at the exact same step and are repeatable.
With "no globals" afl-fuzz this is not the case. The results are all over the place although all instances are set with the same -s value.

This can either be a small issue that the rng is not initialized as it should - or an indicator that there is a big bug somewhere hidden fucking up the mutation.

I will check later if I can find out what the issue is, @andreafioraldi you know the mutation part better than me now I think so if you could have a look as well that would be great

**Comment by andreafioraldi** [comment]
`fsrv_init() checks if use_stdin is 1` this is a dirty hack, I'll find a better solution in the next days (maybe this evening).

Regards the mutation yes this is a problem, but the bug can be in any part of the code that calls UR not only in fuzz_one. I'll take a look.

**Comment by domenukk** [comment]
Why not always initialize?
Init is called at the very beginning anyway, the variables will be overwritten afterwards.

**Comment by vanhauser-thc** [comment]
there are 3 clients to the forkserver -> tmin, showmap and fuzz. fuzz performs its own init and the adding to the list function, tmin and showmap call fsrv_init which did nothing else than calling the adding to the list function.

hence I think we can remove the if() check there and hard code the initialization.

that was before I checked who is doing what.

**Comment by domenukk** [comment]
In the long run we should probably initialize the forkserver inside the forkserver method, with all consumers passing in the variables.
that way other tools can use the forkserver more easily and we can swap it out against different implementations

**Comment by vanhauser-thc** [comment]
I checked the random init - it is still the same and all var assignments etc. look good.
As with the same -s value the "non global" afl-fuzz produces different results it seems like there is a bug in the mutator

**Comment by domenukk** [comment]
Do you run MOpt-based mutators? These were the largest change I had to make.
Apart from that, either one variable now that was supposed to be local now uses `afl_state_t` by accidents, or the different results are simply cause by more allocations that may also call random()?

**Comment by vanhauser-thc** [comment]
No, not MOpt ... "classic" ... also no radamsa or custom

**Comment by vanhauser-thc** [comment]
@domenukk @andreafioraldi @hexcoder- we really need to find this issue. I have a longer train ride today where I will try to dig deeper into it ... please help out and have a look too if you have the time

**Comment by vanhauser-thc** [comment]
OK, one step forward:

there is no bug in the mutation. The mutations are exactly the same if the `-s` option is used - I verified this with afl-fuzz-document (`make document`).

However: post-"no globals" reports 77 paths on a given test case, whereas pre-"no globals" reports 75 paths. Same instrumented binary, same mutations being performed. and different post-"no-globals" runs can result in different paths for the same test setup (e.g. the 2nd run showed 76 paths ...)

On the other hand the queue entries are exactly the same, same number of entries with the same contents. 

So it seems to be that the paths variable is not initialized? 

at least its not critical and a minor thing. removing the "important" flag, but still needs to be fixed before we do the next release

**Comment by vanhauser-thc** [comment]
the two variables that become wrong are: afl->pending_not_fuzzed and afl->queued_paths. They are between +0 to +2 higher in my tests than the real value they should be.

**Comment by vanhauser-thc** [comment]
I think I found the issue.
the UI is rendered at different times when stop_soon is reached, hence a different state is displayed in the end. I will fix this by rendering it one last time before the exit print screen message is written

**Comment by vanhauser-thc** [comment]
fixed with 61ba214
