### ISSUE TITLE
LTO deprected setAlignment warning

### ISSUE THREAD

**Issue by andreafioraldi** [vanhauser-thc/AFLplusplus#249]
I got this warning when building in fuzzbench

```
afl-llvm-lto-instrumentation.so.cc:381:18: warning: 'setAlignment' is deprecated: Please use `void setAlignment(MaybeAlign Align)` [-Wdeprecated-declarations]
    AFLFinalLoc->setAlignment(4);
                 ^
/usr/local/include/llvm/IR/GlobalObject.h:81:3: note: 'setAlignment' has been explicitly marked deprecated here
  LLVM_ATTRIBUTE_DEPRECATED(void setAlignment(unsigned Align),
  ^
/usr/local/include/llvm/Support/Compiler.h:296:23: note: expanded from macro 'LLVM_ATTRIBUTE_DEPRECATED'
  decl __attribute__((deprecated(message)))
                      ^
1 warning generated.
```

**Comment by andreafioraldi** [comment]
Got also `[!] WARNING: Mistyped AFL environment variable: AFL_LLVM_INSTRIM_SKIPSINGLEBLOCK=1`
That is wrong, I coped the env var from the Reame

**Comment by andreafioraldi** [comment]
There is also AFL_QUIET so this warning should not be here anyway

**Comment by vanhauser-thc** [comment]
fuzzbench align warning: which llvm version is that?

mistyped env var warning:
this might be because you use a specific checkout? because in trunk:
```
$ grep AFL_LLVM_INSTRIM_SKIPSINGLEBLOCK include/*.h
envs.h:    "AFL_LLVM_INSTRIM_LOOPHEAD", "AFL_LLVM_INSTRIM_SKIPSINGLEBLOCK",
```

I agree on the warning -> afl_quiet, just added that.

**Comment by andreafioraldi** [comment]
idk which LLVM version is, it is the OSS-Fuzz docker.
fuzzbench wants a specific checkout, I updated it now to the latest commit in master.

**Comment by andreafioraldi** [comment]
Probably is LLVM 8 I guess

**Comment by vanhauser-thc** [comment]
That might be llvm 8. In the current state lto only builds with 9+ because the SplitEdge function produces bugs on older llvm versions
