### ISSUE TITLE
gcc_plugin crash

### ISSUE THREAD

**Issue by vanhauser-thc** [vanhauser-thc/AFLplusplus#25]
this happens in a lot of larger projects when compiling with the gcc_plugin - afl-gcc-fast/afl-g++-fast :
```
[+] Instrumented 11 locations in TIFFInitJPEG
during GIMPLE pass: evrp
tif_jpeg.c: In function ‘JPEGFixupTagsSubsamplingSec’:
tif_jpeg.c:2388:1: internal compiler error: Segmentation fault
 }
 ^
0x7ffff758e83f ???
	/build/glibc-vjB4T1/glibc-2.28/signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
0x7ffff757b09a __libc_start_main
	../csu/libc-start.c:308
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <file:///usr/share/doc/gcc-8/README.Bugs> for instructions.
make[2]: *** [Makefile:696: tif_jpeg.lo] Error 1
```

to reproduce:
```
wget http://download.osgeo.org/libtiff/tiff-4.0.4.tar.gz
tar xzf tiff-4.0.4.tar.gz
cd tiff-4.0.4
CC=afl-gcc-fast CXX=afl-g++-fast ./configure --disable-shared
make
```

**Comment by hexcoder-** [comment]
Its always the

#include "tiffiop.h"

that causes the crashes for me.

If i comment that out, the compile pass does not crash, but fails to 
link later...

Strange.

Heiko

**Comment by hexcoder-** [comment]
I have trimmed down in tif_packbits.c one case of 

> GIMPLE pass switchconv

 crash to this meaningless piece of code:
```
int
PackBitsEncode(signed long cc)
{
 enum { LITERAL, LITERAL_RUN } state;
 while (cc > 0) {
  for (; cc > 0 && cc % 42; )
   cc++;
 again:
  switch (state) {
  case LITERAL:
    if (cc > 128) {
     goto again;
    }
   break;
  case LITERAL_RUN:
   goto again;
  }
 }
 return (1);
}

```
The 10th instrumentation of 11 locations produces the crash.

**Comment by vanhauser-thc** [comment]
also if optimization is disabled it does not break: AFL_DONT_OPTIMIZE=1

**Comment by vanhauser-thc** [comment]
gcc_plugin is inefficient and broken and needs to be rewritten anyway. issue closed

**Comment by hexcoder-** [comment]
The crash seems to be fixed by https://github.com/vanhauser-thc/AFLplusplus/commit/4ce57e978fd2d8a6f572d7d06761b31644e3c9c8 now. A lot of TODOs left...
