### ISSUE TITLE
Error building  gcc_plugin

### ISSUE THREAD

**Issue by ChakshuGupta** [vanhauser-thc/AFLplusplus#255]
![afl-gcc_plugin](https://user-images.githubusercontent.com/6474622/76522943-ca7fbe80-6467-11ea-9ae2-3845d45e822c.png)

"make all" command failed when trying to build "gcc_plugin"

Env - Ubuntu 18.04
gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
clang version 6.0.0-1ubuntu2

**Comment by andreafioraldi** [comment]
Install the gcc headers, the error is clear

**Comment by fuzzah** [comment]
for dpkg based distros:
`# apt install gcc-9-plugin-dev`

for rpm based distros:
`# yum install devtoolset-9-gcc-plugin-devel`

**Comment by ChakshuGupta** [comment]
Thanks. Maybe this can be added to the build instructions?

**Comment by vanhauser-thc** [comment]
You mean like in the README.md of gcc_plugin? well ...

```
# 2) How to use

In order to leverage this mechanism, you need to have modern enough GCC
(>= version 4.5.0) and the plugin headers installed on your system. That
should be all you need. On Debian machines, these headers can be acquired by
installing the `gcc-<VERSION>-plugin-dev` packages.
```

;)
