### ISSUE TITLE
Pull "changes" from upstream afl (?)

### ISSUE THREAD

**Issue by domenukk** [vanhauser-thc/AFLplusplus#29]
Google just released AFL on github officially, apparently.
The code lives here:
https://github.com/google/AFL
The version has been bumped to 2.5**3**b. 
Should afl++ merge the one line of readme changes and adapt to the upstream versioning?

**Comment by vanhauser-thc** [comment]
it was about time :)
but I doubt anything else will happen in that repository. but lets see.

funny that they do a 2.53b. our 2.53c is likely coming tomorrow ;)

the changes are just putting link markups into the README and renaming it to README.md. 
thats something we could pull as its on our TODO list as well.

**Comment by hexcoder-** [comment]
I would copy the new travis CI file, looks useful.

Heiko

**Comment by vanhauser-thc** [comment]
they were thorough with the copyright stuff but very sloppy with the documentation, also the readme.md is so incomplete with the links ... 

its done, but mostly by hand.
