### ISSUE TITLE
Python mode mutators

### ISSUE THREAD

**Issue by vanhauser-thc** [vanhauser-thc/AFLplusplus#3]
Implement this:
https://github.com/choller/afl/blob/master/docs/mozilla/python_modules.txt

**Comment by vanhauser-thc** [comment]
After inspecting this I am unsure if this is a good thing to add.
Python will have a pretty strong negative impact on performance, and a post processing library via AFL_POST_LIBRARY is way faster.

If anyone wants this please describe your case and why afl's post processing capabilities would be worse.

**Comment by ngregoire** [comment]
I used the Python mutators a lot, and the use-case is very different from standard post processing ones. A common scenario is fuzzing an application using a structured text-based format as its input, like ImageMagick with SVG files or libxslt with XSLT files. In both situations, the structure _must_ be valid (from the point-of-view of the XML parser). I heard that some people use similar strategies for JSON inputs.

I implemented a XML-mutator (acting on trees, nodes, attributes, ...) using this Python binding and successfully used it on different targets (browsers, images processors, ...). One example, targeting libxslt + Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=930663

Regarding performances, the script is loaded only once and costly initialization should be done in init(), with fuzz() being as fast as possible. My implementation of fuzz() will sometimes access an in-memory DB, but that doesn't make reaching hundreds of iterations per second unfeasible.

These efforts were documented in a talk published at NullCon in 2017:
https://www.agarri.fr/docs/XML_Fuzzing-NullCon2017-PUBLIC.pdf

**Comment by vanhauser-thc** [comment]
@ngregoire do you have to proposal on how to do solve the afl-fuzz compiling? as it requires an external library and we want to avoid a ./configure thing and few people have this ...

To add the python stuff into afl-fuzz is the easy thing.

**Comment by ngregoire** [comment]
From a quick look at afl-fuzz.c, it seems that not defining USE_PYTHON could be enough:

    #ifdef USE_PYTHON
    #include <Python.h>
    ...

Maybe we should invite @choller, as he knows better than us ;-)

**Comment by vanhauser-thc** [comment]
@ngregoire yeah the -DUSE_PYTHON would be enough - but how to do that without much hassle?

either "make" for normal and "make python" for building with python support? a ./configure would be the easiest, but I want to try to avoid a ./configure ...

**Comment by vanhauser-thc** [comment]
@ngregoire @choller I added the support plus some nifty Makefile magic to autodetect Python 2.7 dev ... can you please have a look that is correctly implementd and working for you?

**Comment by vanhauser-thc** [comment]
@ngregoire @choller can you please test it? So I can close the issue.

and if you have a few more examples that would be helpful for people :) I added the one from choeller's github

**Comment by ngregoire** [comment]
I can't test before ~ a week. Regarding examples, I can't share my own implementation, but I'll consider publishing a highly trimmed-down version.

**Comment by vanhauser-thc** [comment]
@ngregoire ok, good to know it will take about a week, thanks. and any trimmed down version is still better than none :)

**Comment by ngregoire** [comment]
It tested it, and it works perfectly fine!

Auto-detection of Python 2.7 during compilation + I simply had to set two environment variables:

    export AFL_PYTHON_MODULE="script_without_py_extension"
    export PYTHONPATH="/where/the/script/is/"

A minimalist XML mutator + its wrapper script are attached. This version of the mutator only removes elements or fuzz attributes values. Both files should be renamed (remove the "txt" extension) and put in the same directory (here "/where/the/script/is/").

[wrapper_afl_min.py.txt](https://github.com/vanhauser-thc/AFLplusplus/files/3352913/wrapper_afl_min.py.txt)
[XmlMutatorMin.py.txt](https://github.com/vanhauser-thc/AFLplusplus/files/3352914/XmlMutatorMin.py.txt)

**Comment by vanhauser-thc** [comment]
perfect, thank you!
