### ISSUE TITLE
Showmap fix may break cmin

### ISSUE THREAD

**Issue by andreafioraldi** [vanhauser-thc/AFLplusplus#34]
@vanhauser-thc I've just seen your change to showmap and it is useful to see the raw
tuples but this IMO will break afl-cmin that uses showmap with manipulated tuples.
Your patch skips the count_class_binary filter used by cmin without -e.
I will add ASAP an option to showmap for not manipulated tuples and left the old behaviour by default to not break cmin and other tools built on top of showmap.

**Comment by vanhauser-thc** [comment]
yeah that might be a good idea then. have never checked how afl-cmin actually works ...

**Comment by andreafioraldi** [comment]
Fixed with https://github.com/vanhauser-thc/AFLplusplus/commit/7a608d1346f5e4c18f37ba3d6e2a3ff6d691c551

The option to show the not manipulated map is -r now.
