### ISSUE TITLE
The command to get the clang version in the llvm_mode Makefile is not correct

### ISSUE THREAD

**Issue by GoodDayGeorge** [vanhauser-thc/AFLplusplus#43]
#44

**Comment by GoodDayGeorge** [comment]
#44

**Comment by GoodDayGeorge** [comment]
![image](https://user-images.githubusercontent.com/36875177/62819864-da5fb900-bb8d-11e9-9c89-e6bee7f88c6f.png)

**Comment by hexcoder-** [comment]
Thanks! Yes, this happens when the install directory also contains the triple.

**Comment by hexcoder-** [comment]
fixed with your PR
