### ISSUE TITLE
QEMU build breaks on new glibc

### ISSUE THREAD

**Issue by floyd-fuh** [vanhauser-thc/AFLplusplus#58]
When using ubuntu 19.10 and AFL++ commit c124576a4dc00e31ad5cad118098f46eaa29cd17 everything worked perfectly fine before, but I think with the new glibc in ubuntu 19.10 it fails (see link below why I think that). I tried upgrading my Docker image to the new a67d86c6e2ca58db81f2ddf6d0a4c837be88271d commit (so I don't think it is the new AFL++ but a glibc/QEMU problem):

```
$ apt-get update && apt-get -y install build-essential clang git python2.7-dev python2.7 && git clone https://github.com/vanhauser-thc/AFLplusplus.git /afl && cd /afl/ && git reset --hard a67d86c6e2ca58db81f2ddf6d0a4c837be88271d && make
[...]
$ cd /afl/libdislocator/ && make
[...]
$ cd /afl/llvm_mode && ln -s /usr/bin/llvm-config-? /usr/bin/llvm-config && make
[...]
$ cd /afl/ && make install
$ unset AFL_CC AFL_CXX AFL_AS && apt-get update && apt-get -y install libtool-bin wget bison libglib2.0-dev libpixman-1-dev python && cd /afl/qemu_mode && ./build_qemu_support.sh && cd /afl/ && make install
[...]
  CC      x86_64-linux-user/accel/tcg/user-exec-stub.o
  CC      x86_64-linux-user/linux-user/main.o
  CC      x86_64-linux-user/linux-user/syscall.o
/afl/qemu_mode/qemu-3.1.0/linux-user/syscall.c:256:16: error: static declaration of 'gettid' follows non-static declaration
  256 | _syscall0(int, gettid)
      |                ^~~~~~
/afl/qemu_mode/qemu-3.1.0/linux-user/syscall.c:187:13: note: in definition of macro '_syscall0'
  187 | static type name (void)   \
      |             ^~~~
In file included from /usr/include/unistd.h:1170,
                 from /afl/qemu_mode/qemu-3.1.0/include/qemu/osdep.h:90,
                 from /afl/qemu_mode/qemu-3.1.0/linux-user/syscall.c:20:
/usr/include/x86_64-linux-gnu/bits/unistd_ext.h:34:16: note: previous declaration of 'gettid' was here
   34 | extern __pid_t gettid (void) __THROW;
      |                ^~~~~~
make[1]: *** [/afl/qemu_mode/qemu-3.1.0/rules.mak:69: linux-user/syscall.o] Error 1
make[1]: *** Waiting for unfinished jobs....
  LINK    ivshmem-server
  LINK    qemu-nbd
  LINK    qemu-img
make: *** [Makefile:483: subdir-x86_64-linux-user] Error 2
```

This seems to be this one:
https://lists.gnu.org/archive/html/qemu-devel/2019-04/msg01314.html

If I understand it correctly this is more of a QEMU problem than an AFL++ problem, however, AFL++ still uses QEMU 3.1.0 instead of 3.1.1. So squeezing the following in:

```
sed -i "s/3.1.0/3.1.1/g" build_qemu_support.sh && sed -i "s/0318f2b5a36eafbf17bca0f914567dfa5e8a3cd6ff83bb46fe49a0079cd71ddd3ec4267c6c62a03f9e26e05cc80e6d4b/28ff22ec4b8c957309460aa55d0b3188e971be1ea7dfebfb2ecc7903cd20cfebc2a7c97eedfcc7595f708357f1623f8b/g" build_qemu_support.sh
```

It didn't compile either :( So either QEMU support will be broken in newer glibc or we patch AFL++ or QEMU 4 support is ready soon. Unfortunately I can also not use an older version of 9.10, because in Docker images the version specification "9.10" is as granular as it gets.

Patching AFL++ shouldn't be too hard, as there is already a syscall.diff patch...

Off-topic: I'm currently writing a Docker image for AFL++. I think AFL++ would really profit from a stable build environment, where tests could be run as well to make sure AFL++ still works correctly. With Docker multi-stage images I was able to build different images, with various features and different compile times if the Docker image would need updating. It was also only one command (rebuild the docker) to find the above issue. Moreover, I think it would really benefit the community, as installing AFL++, libdislocator, llvm_mode, recidivm, QEMU mode, afl-dyninst is probably already a problem for beginners. Having the same build environment would be the first step to simplify performance comparisons (together with -E -V options). With the Docker image it would as well be very easy to do some sort of continuous integration and building the newest release overnight and run additional tests... I'll let you know some more about the Docker soon

**Comment by andreafioraldi** [comment]
Hi, thank for for the report.
Can you try to compile QEMU 3.1.1? If the bug is fixed there there no problems to port the instrumentation on this version.
QEMU 4, on the other hand, is very problematic (see https://github.com/vanhauser-thc/AFLplusplus/issues/2).

**Comment by andreafioraldi** [comment]
On Ubuntu 18 the patches are applied without problems to QEMU 3.1.1 and the build is fine.
Check the branch https://github.com/vanhauser-thc/AFLplusplus/tree/qemu_3.1.1

**Comment by floyd-fuh** [comment]
Hi Andrea, sorry if my original report wasn't clear on that. 3.1.1 does not work:

> So squeezing the following in:
> 
> ```
> sed -i "s/3.1.0/3.1.1/g" build_qemu_support.sh && sed -i "s/0318f2b5a36eafbf17bca0f914567dfa5e8a3cd6ff83bb46fe49a0079cd71ddd3ec4267c6c62a03f9e26e05cc80e6d4b/28ff22ec4b8c957309460aa55d0b3188e971be1ea7dfebfb2ecc7903cd20cfebc2a7c97eedfcc7595f708357f1623f8b/g" build_qemu_support.sh
> ```
> 
> It didn't compile either :(

Here's the output:

```
  CC      x86_64-linux-user/linux-user/main.o
  CC      x86_64-linux-user/linux-user/syscall.o
/afl/qemu_mode/qemu-3.1.1/linux-user/syscall.c:256:16: error: static declaration of 'gettid' follows non-static declaration
  256 | _syscall0(int, gettid)
      |                ^~~~~~
/afl/qemu_mode/qemu-3.1.1/linux-user/syscall.c:187:13: note: in definition of macro '_syscall0'
  187 | static type name (void)   \
      |             ^~~~
In file included from /usr/include/unistd.h:1170,
                 from /afl/qemu_mode/qemu-3.1.1/include/qemu/osdep.h:90,
                 from /afl/qemu_mode/qemu-3.1.1/linux-user/syscall.c:20:
/usr/include/x86_64-linux-gnu/bits/unistd_ext.h:34:16: note: previous declaration of 'gettid' was here
   34 | extern __pid_t gettid (void) __THROW;
      |                ^~~~~~
make[1]: *** [/afl/qemu_mode/qemu-3.1.1/rules.mak:69: linux-user/syscall.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:483: subdir-x86_64-linux-user] Error 2
```

So unfortunately updating to 3.1.1 is not sufficient :(

**Comment by andreafioraldi** [comment]
Ok, I'm backporting the patch to QEMU 3.1.1, wait some minutes (I need you as tester cause I don't have an Ubuntu 19.10 VM ready).

**Comment by andreafioraldi** [comment]
Done, clone the qemu_3.1.1 branch and test it please.
On Ubuntu 18.04 nothing change and it is good.

**Comment by andreafioraldi** [comment]
Regards the Dockerfile, seems a good idea. @vanhauser-thc @hexcoder- I added a
`distrib` option to the root Makefile of the qemu_3.1.1 branch that builds all the optional modules (tokencap, dislocator, llvm, qemu and unicorn).
Now `make distrib` builds all.

**Comment by floyd-fuh** [comment]
`[+] Build process successful!`
in a second I'll let you know if it also runs correctly (finds paths)

**Comment by floyd-fuh** [comment]
> Regards the Dockerfile, seems a good idea. @vanhauser-thc @hexcoder- I added a
> `distrib` option to the root Makefile of the qemu_3.1.1 branch that builds all the optional modules (tokencap, dislocator, llvm, qemu and unicorn).
> Now `make distrib` builds all.

if I might suggest, I think make distrib is good, but a lot of people will also just fuzz open source projects where the source is available. These people do not necessarily need to wait for the very long compilation times (and disc usage) of qemu and unicorn (and afl-dyninst for that matter). So in my Docker there is an afl-base (afl++, dislocator, tokencap, llvm) and afl-blackbox (based on afl-base with qemu, unicorn and afl-dyninst). So maybe a `make whitebox` and `make blackbox` (although `make blackbox` is the same as `make distrib`...)

**Comment by andreafioraldi** [comment]
I'm going to push `make binary-only` and `make source-only`.
If you confirm that the execution/seconds and the coverage found is meaningful I'm ready to merge in master.

**Comment by andreafioraldi** [comment]
Ah, as last thing, as I understand you will include in the docker image other tools alongside AFL++ so please don't name the image on Docker Hub AFL++ cause it can be misleading.
Maybe choose a name like AFLplusplus_suite or similar.

**Comment by vanhauser-thc** [comment]
@floyd-fuh  afl++_suite sounds cool :)
out of curiousity - are you compiing for dynsinst10 master?
I havent lookt at it for a few months - is the instrumentation now better (less "crashy")?

**Comment by floyd-fuh** [comment]
> out of curiousity - are you compiing for dynsinst10 master?
> I havent lookt at it for a few months - is the instrumentation now better (less "crashy")?

No, not master, but dyninst 10.1.0:

```
apt-get update && apt-get -y install curl cmake && \
	curl -L https://github.com/dyninst/dyninst/archive/v10.1.0.tar.gz | tar zxf - && \
	cd dyninst-10.1.0 && mkdir build && cd build && cmake .. && \
    make && make install && \
	echo "Another RUN for afl-dyninst - do not use https://github.com/talos-vulndev/afl-dyninst.git" && \
	apt-get update && apt-get -y install libiberty-dev && \
	git clone https://github.com/vanhauser-thc/afl-dyninst.git /afl-dyninst && cd /afl-dyninst && \
	git reset --hard c2f14ea01b9060d0b95719ff01d2ac6a2b38dcb3 && \
	ln -s /afl afl && make && \
	cd /afl-dyninst && cp afl-dyninst /usr/local/bin && cp libAflDyninst.so /usr/local/lib && \
	echo "/usr/local/lib" > /etc/ld.so.conf.d/dyninst.conf && ldconfig && \
	rm -rf /dyninst-*
```
This one seems fine, but I've only run a couple of tests which looked good from my point.

**Comment by vanhauser-thc** [comment]
@floyd-fuh 
why git reset --hard c2f14ea01b9060d0b95719ff01d2ac6a2b38dcb3 in afl-dyninst?
did I introduce a bug?

**Comment by floyd-fuh** [comment]
> why git reset --hard c2f14ea01b9060d0b95719ff01d2ac6a2b38dcb3 in afl-dyninst?
> did I introduce a bug?

Not at all. But Docker builds should be as reproducible as possible. Consider it being a manual update procedure: Instead of automatically using the latest master (and maybe breaking the Docker build, for example like the bug above which is only reproducible on ubuntu 19.10), I always use a specific commit. I would also keep it that way and whenever you have a larger release, I can change the commit which I want to use. I could also just use "releases" of afl-dyninst instead.

**Comment by vanhauser-thc** [comment]
@floyd-fuh thanks, makes sense!
then a second Dockerfile with bleeding edge would be beneficial too
