### ISSUE TITLE
AFL for android hidl

### ISSUE THREAD

**Issue by JoeyJiao** [vanhauser-thc/AFLplusplus#62]
Hi,
Android now uses hidl (client/server mode) stated here https://source.android.com/devices/architecture/hidl-cpp.

If I enable afl for client and server and when I run fuzz for client, it will only show paths of client. I know there is a called llvm persist mode, but I can hardly find anywhere in the hidl mode to put the persist code in hidl server.

Any idea or experience?

**Comment by vanhauser-thc** [comment]
None of us three maintainers work with Android, so actually no clue what you are talking about ;)

but maybe if you elaborate what you mean by client, server, hidl ... ?

**Comment by andreafioraldi** [comment]
If you can use the client code in the server a common pattern is to create a client thread with a persistent loop that connects to the server in the same process. In this way both client and server are instrumented.
As this is a question about a specific software and not a bug/feature of the fuzzer I suggest you to use the AFL Google group and not the AFL++ issue section for such type of questions.
