### ISSUE TITLE
Compilation artifacts not listed in .gitignore

### ISSUE THREAD

**Issue by XairGit** [vanhauser-thc/AFLplusplus#66]
There appears to be a number of compilation artifacts which are not listed in .gitignore, and as a result appear as untracked files in the AFLplusplus git repo after compilation.

These files are as follows:
* afl-analyze.8
* afl-clang-fast++.8
* afl-clang-fast.8
* afl-cmin.8
* afl-fuzz.8
* afl-gcc.8
* afl-gotcpu.8
* afl-plot.8
* afl-showmap.8
* afl-system-config.8
* afl-tmin.8
* afl-whatsup.8
* qemu_mode/libcompcov/compcovtest

These appeared on my system after compiling AFLplusplus by running `make distrib` and then `sudo make install`

I have created #65 which adds these files to the .gitignore file, if for some reason these only appeared on my system and not for other people feel free to close this issue and reject the PR.

**Comment by hexcoder-** [comment]
Thanks, it is included now.
