### ISSUE TITLE
Suspicious crash of QEMU with FFmpeg on old Debian

### ISSUE THREAD

**Issue by andreafioraldi** [vanhauser-thc/AFLplusplus#69]
I'm trying to fuzz FFmpeg on a server with `Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux`.

I have a suspicious segfault of QEMU in afl-fuzz, running the binary with afl-qemu-trace works fine.
Output with debug child out:
```
ffmpeg version N-95006-g76f861bbb7 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: 
  libavutil      56. 35.100 / 56. 35.100
  libavcodec     58. 58.101 / 58. 58.101
  libavformat    58. 33.100 / 58. 33.100
  libavdevice    58.  9.100 / 58.  9.100
  libavfilter     7. 58.102 /  7. 58.102
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
Trailing options were found on the commandline.
[avi @ 0x40049f6380] Could not find codec parameters for stream 0 (Video: mpeg4 (FMP4 / 0x34504D46), none, 1x1): unspecified pixel format
Consider increasing the value for the 'analyzeduration' and 'probesize' options
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
```

On my Ubuntu 18 laptop it works fine without crashes, can you reproduce the issue?
[attachments.tar.gz](https://github.com/vanhauser-thc/AFLplusplus/files/3658644/attachments.tar.gz)

**Comment by andreafioraldi** [comment]
Seems related with CompCov. Without CompCov or with AFL_COMPCOV_LEVEL=1 works fine, AFL_COMPCOV_LEVEL=2 cause the crash. Of course AFL_COMPCOV_LEVEL=2 works fine on my laptop and the issue is only in the Debian server.

**Comment by hexcoder-** [comment]
Hi,

I will see, if I get some time over the weekend to look into it.

Regards, Heiko

**Comment by vanhauser-thc** [comment]
@hexcoder- @andreafioraldi  is this still open?

**Comment by andreafioraldi** [comment]
In theory yes... but on Ubuntu 18.04 with the same binary I cannot trigger the bug. Probably some QEMU dark magic, I close the issue.
