### ISSUE TITLE
Linker issue: local symbol __afl_area_ptr in afl-llvm-rt.o is referenced by DSO

### ISSUE THREAD

**Issue by floyd-fuh** [vanhauser-thc/AFLplusplus#77]
Hi guys,

I'm trying to compile OpenJDK with AFL++. In essence I'm compiling like this with jdk10: https://hg.openjdk.java.net/jdk-updates/jdk9u/raw-file/tip/common/doc/building.html#tldr-instructions-for-the-impatient . Yes I know that's probably not the easiest task, until I got this far I had to include several bug fixes for the code already. E.g. it doesn't accept CFLAGS, not even via the configure argument --with-extra-cflags and --with-extra-cxxflags that was made for it: https://bugs.openjdk.java.net/browse/JDK-8156967 . I "fixed" it by search/replacing CFLAGS/CXXFLAGS in the make scripts after the configure instruction. It feels like I'm the only person on the planet compiling 

I've got through the compiling stage but I'm not getting linker error. I guess I need to fix LDFLAGS as well. Any ideas how I could resolve the following error? I guess I need to 

```
ERROR: Build failed for target 'images' in configuration 'linux-x86_64-normal-server-release' (exit code 2) 

=== Output from failing command(s) repeated here ===
* For target support_native_java.corba_idlj_objs_BUILD_LAUNCHER_idlj_link:
/usr/bin/ld: /jdk10/build/linux-x86_64-normal-server-release/support/modules_cmds/java.corba/idlj: local symbol `__afl_area_ptr' in /afl//afl-llvm-rt.o is referenced by DSO
/usr/bin/ld: final link failed: bad value
clang: error: linker command failed with exit code 1 (use -v to see invocation)
* For target support_native_java.desktop_appletviewer_objs_BUILD_LAUNCHER_appletviewer_link:
/usr/bin/ld: /jdk10/build/linux-x86_64-normal-server-release/support/modules_cmds/java.desktop/appletviewer: local symbol `__afl_area_ptr' in /afl//afl-llvm-rt.o is referenced by DSO
/usr/bin/ld: final link failed: bad value
clang: error: linker command failed with exit code 1 (use -v to see invocation)

* All command lines available in /jdk10/build/linux-x86_64-normal-server-release/make-support/failure-logs.
=== End of repeated output ===
```

Here's the exact command that fails:

```
# /usr/local/bin/afl-clang -Wl,--allow-shlib-undefined -Wl,-rpath,\$ORIGIN/../lib/jli -Wl,-rpath,\$ORIGIN/../lib -L/jdk10/build/linux-x86_64-normal-server-release/support/modules_libs/java.base/jli -Wl,-version-script=/jdk10/jdk/make/mapfiles/launchers/mapfile-x86_64 -o /jdk10/build/linux-x86_64-normal-server-release/support/modules_cmds/java.corba/idlj /jdk10/build/linux-x86_64-normal-server-release/support/native/java.corba/idlj_objs/main.o -lz -lpthread -ljli -ldl -lc -v
afl-clang-fast++2.54d by <lszekeres@google.com>
clang version 9.0.0-2 (tags/RELEASE_900/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/9
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/usr/bin/ld" -z relro --hash-style=gnu --build-id --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o /jdk10/build/linux-x86_64-normal-server-release/support/modules_cmds/java.corba/idlj /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crt1.o /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crti.o /usr/bin/../lib/gcc/x86_64-linux-gnu/9/crtbegin.o -L/jdk10/build/linux-x86_64-normal-server-release/support/modules_libs/java.base/jli -L/usr/bin/../lib/gcc/x86_64-linux-gnu/9 -L/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu -L/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../lib64 -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib64 -L/usr/lib/x86_64-linux-gnu/../../lib64 -L/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../.. -L/usr/lib/llvm-9/bin/../lib -L/lib -L/usr/lib --allow-shlib-undefined -rpath "\$ORIGIN/../lib/jli" -rpath "\$ORIGIN/../lib" -version-script=/jdk10/jdk/make/mapfiles/launchers/mapfile-x86_64 /jdk10/build/linux-x86_64-normal-server-release/support/native/java.corba/idlj_objs/main.o -lz -lpthread -ljli -ldl -lc /afl//afl-llvm-rt.o -lgcc --as-needed -lgcc_s --no-as-needed -lc -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/bin/../lib/gcc/x86_64-linux-gnu/9/crtend.o /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crtn.o
/usr/bin/ld: /jdk10/build/linux-x86_64-normal-server-release/support/modules_cmds/java.corba/idlj: local symbol `__afl_area_ptr' in /afl//afl-llvm-rt.o is referenced by DSO
/usr/bin/ld: final link failed: bad value
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by floyd-fuh** [comment]
The shared object `/jdk10/build/linux-x86_64-normal-server-release/support/modules_libs/java.base/jli/libjli.so` in the above `ld` command seems to include a reference to `__afl_area_ptr` (as well as the binary `/jdk10/build/linux-x86_64-normal-server-release/support/native/java.corba/idlj_objs/main.o`). But that is expected given that instrumentation should take place of those parts as well. I don't see why `ld` would complain that `libjli.so` already has a reference to `__afl_area_ptr` and especially why that should be a local symbol.

**Comment by andreafioraldi** [comment]
@hexcoder- what do you think?

**Comment by andreafioraldi** [comment]
@floyd-fuh are you able to compile with the old AFL?

**Comment by hexcoder-** [comment]
Hmm, when i try to configure it with

`CC=afl-clang-fast CXX=afl-clang++-fast bash ./configure`

it complains with
```
checking for afl-clang-fast... /usr/local/bin/afl-clang-fast
checking resolved symbolic links for CC... no symlink
configure: The C compiler (located as /usr/local/bin/afl-clang-fast) does not seem to be the required gcc compiler.
configure: The result from running with --version was: ""
configure: error: A gcc compiler is required. Try setting --with-tools-dir.
configure exiting with result code 1
```

**Comment by hexcoder-** [comment]
Sorry, but OpenJDK9 does not compile for me even without using AFL++ on Ubuntu 18.04 with gcc 7.4.0. They use -Werror and call a deprecated function readdir_r, which would normally issue only a warning. But now it is promoted to error. So compilation stops.

If it does for you too, you should ask the OpenJDK folks for support.

**Comment by vanhauser-thc** [comment]
@hexcoder-  ähm ... he is trying to compile jdk10 not jdk9 that you tried :)

also in cases that configure is complaining about stuff that afl-gcc/llvm_mode cant do I set set CC=cc CXX=c++, and when configure I set them to gcc, and when compiling I set /bin/cc to afl-clang-fast. easy :)

trying this now.

**Comment by hexcoder-** [comment]
@vanhauser-thc I used the links given above. So it was jdk10 then, not jdk9.

I am very hesitant to do such '**easy**' trickery without understanding the reason behind the rejection. In my experience that introduces inconsistency and is an easy way to shoot yourself in the foot. 

Good luck!

**Comment by vanhauser-thc** [comment]
OK I cant even get jdk10 compiled with normal gcc-8 and clang-8 does even abort earlier complaining about bad code.
sorry I am out there ... :)

**Comment by floyd-fuh** [comment]
> So, clang and afl-clang-fast is not acceptable for OpenJDK. You should switch to afl-gcc/afl-g++ and retry.

You have to use `--with-toolchain-type=clang` for the configure command.

> Sorry, but OpenJDK9 does not compile for me even without using AFL++ on Ubuntu 18.04 with gcc 7.4.0. They use -Werror and call a deprecated function readdir_r, which would normally issue only a warning. But now it is promoted to an error. So compilation stops.
> 
> If it does for you too, you should ask the OpenJDK folks for support.

Of course I could, but the error report I find from 2016 saying that the compilation process is broken (see link in my original post) and nobody doing anything about it doesn't make me want to do that. So I wrote my own ugly sed "fixes", see below. And while they might be ugly and maybe not even fully correct, I highly doubt that they are the reason for the linker issue I have at the moment.

I am looking at the security of Java. I was as surprised as you that it doesn't compile easily. This entire experience gets me a very bad feeling, as this tells me only very few people or nobody is compiling with any other CFLAGS, so probably also not with ASAN and similar things. That's why Java is an interesting target.

> @floyd-fuh are you able to compile with the old AFL?

I didn't try. Mind thought it is a linking problem, not compilation, so the question is if there are any special requirements for the linking with AFL.

So all in all, Java is a beast. The link in the original post is a hint that it's a mess. I didn't expect you would try to compile it yourself, but thank you for trying (it takes me about 4 hours on my machine to get to the error including an hour of 100% CPU but not a single line printed...).

I wasn't planning to share this originally (I think getting a software to compile with AFL is one of the hardest part of doing fuzzing runs), but I changed my mind. This should get you where I'm stuck at the compilation process on an Ubuntu 19.10 (server) machine where AFL++ is installed in /afl/:

```
apt-get update && apt-get install -y zip unzip mercurial openjdk-8-jdk libx11-dev libxext-dev libxrender-dev libxtst-dev libxt-dev libcups2-dev libfreetype6-dev libasound2-dev && \
	hg clone http://hg.openjdk.java.net/jdk10/jdk10 /jdk10 && \
	cd /jdk10/ && bash get_source.sh && \
	cd /jdk10/ && sed -i 's/CFLAGS := /CFLAGS := -Wno-error -Wno-reserved-user-defined-literal /g' ./hotspot/make/gensrc/*.gmk && \
	sed -i 's/CXXFLAGS := /CXXFLAGS := -Wno-error -Wno-reserved-user-defined-literal /g' ./hotspot/make/lib/*.gmk && \
	sed -i 's/CFLAGS := /CFLAGS := -Wno-error -Wno-reserved-user-defined-literal /g' ./hotspot/make/lib/*.gmk && \
	sed -i 's/CXXFLAGS := /CXXFLAGS := -Wno-error -Wno-reserved-user-defined-literal /g' ./make/common/*.gmk && \
	sed -i 's/CFLAGS := /CFLAGS := -Wno-error -Wno-reserved-user-defined-literal /g' ./make/common/*.gmk && \
	sed -i 's/ADLC_LDFLAGS)/ADLC_LDFLAGS) -static-libgcc -static-libstdc++ -lstdc++/g' ./hotspot/make/gensrc/GensrcAdlc.gmk && \
	sed -i 's/, -1 };/ };/g' ./hotspot/test/native/utilities/test_align.cpp && \
	sed -i 's/entry == false/entry == 0/g' ./hotspot/src/share/vm/code/compiledIC.cpp && \
	sed -i 's/colon + 2/*colon + 2/g' ./hotspot/src/share/vm/compiler/methodMatcher.cpp && \
	sed -i 's/ 0xe0000000,/ 0x0e000000,/g' ./hotspot/src/share/vm/utilities/debug.hpp && \
	sed -i 's/ 0xe0000001,/ 0x0e000001,/g' ./hotspot/src/share/vm/utilities/debug.hpp && \
	sed -i 's/ 0xe0000002/ 0x0e000002/g' ./hotspot/src/share/vm/utilities/debug.hpp && \
	chmod +x configure && BUILD_CC=afl-clang CC=afl-clang BUILD_CXX=afl-clang++ CXX=afl-clang++ ./configure --with-toolchain-type=clang --with-extra-cxxflags="-Wno-error -Wno-reserved-user-defined-literal" --with-extra-cflags="-Wno-error -Wno-reserved-user-defined-literal" && \
	make clean && CFLAGS="-Wno-error -Wno-reserved-user-defined-literal" CXXFLAGS="-Wno-error -Wno-reserved-user-defined-literal" make images
```

I'm also not sure what is going wrong, if it is something in the Java build process or AFL++. But I guess it has something to do with the linking of AFL++ things. Hence the error message and the question about it.

If you don't want to compile it yourself, here's again my question for this open issue (sorry for the too verbose posts of me above):

What do you think could trigger the linker error `local symbol __afl_area_ptr in /afl//afl-llvm-rt.o is referenced by DSO`?

Here's the command that is causing it:

```
"/usr/bin/ld" -z relro --hash-style=gnu --build-id --eh-frame-hdr -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o /jdk10/build/linux-x86_64-normal-server-release/support/modules_cmds/java.corba/idlj /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crt1.o /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crti.o /usr/bin/../lib/gcc/x86_64-linux-gnu/9/crtbegin.o -L/jdk10/build/linux-x86_64-normal-server-release/support/modules_libs/java.base/jli -L/usr/bin/../lib/gcc/x86_64-linux-gnu/9 -L/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu -L/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../lib64 -L/lib/x86_64-linux-gnu -L/lib/../lib64 -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib64 -L/usr/lib/x86_64-linux-gnu/../../lib64 -L/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../.. -L/usr/lib/llvm-9/bin/../lib -L/lib -L/usr/lib --allow-shlib-undefined -rpath "\$ORIGIN/../lib/jli" -rpath "\$ORIGIN/../lib" -version-script=/jdk10/jdk/make/mapfiles/launchers/mapfile-x86_64 /jdk10/build/linux-x86_64-normal-server-release/support/native/java.corba/idlj_objs/main.o -lz -lpthread -ljli -ldl -lc /afl//afl-llvm-rt.o -lgcc --as-needed -lgcc_s --no-as-needed -lc -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/bin/../lib/gcc/x86_64-linux-gnu/9/crtend.o /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crtn.o
/usr/bin/ld: /jdk10/build/linux-x86_64-normal-server-release/support/modules_cmds/java.corba/idlj: local symbol `__afl_area_ptr' in /afl//afl-llvm-rt.o is referenced by DSO
/usr/bin/ld: final link failed: bad value
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by vanhauser-thc** [comment]
I looked on the Internet and it could be either of the two things:
a) there is a bug in the llvm you are using (are you using <= 6.0? Try to switch to 8)
b) the project is dynamically linking to a library that was statically compiled

You could also try to use afl-gcc. It has less speed, but 25% less speed is still better than a project that does not compile ;)

overall - this is not a bug in llvm_mode. so there is nothing we can fix here. (at least IMHO)

**Comment by floyd-fuh** [comment]
> I looked on the Internet and it could be either of the two things:
> a) there is a bug in the llvm you are using (are you using <= 6.0? Try to switch to 8)

That's not it:

```
# llvm-config-9 --version
9.0.0
```

> b) the project is dynamically linking to a library that was statically compiled

hm, that might be it...

> You could also try to use afl-gcc. It has less speed, but 25% less speed is still better than a project that does not compile ;)

I'll try if nothing else works.

> overall - this is not a bug in llvm_mode. so there is nothing we can fix here. (at least IMHO)

Agree that's probably the case. Closing. I'll comment once I find out what's wrong.

**Comment by LuciyVI** [comment]
> ‎Привет, ребята,‎
> 
> ‎Я пытаюсь скомпилировать OpenJDK с помощью AFL++. По сути, я компилирую так с jdk10: ‎[‎https://hg.openjdk.java.net/jdk-updates/jdk9u/raw-file/tip/common/doc/building.html#tldr-instructions-for-the-impatient‎](https://hg.openjdk.java.net/jdk-updates/jdk9u/raw-file/tip/common/doc/building.html#tldr-instructions-for-the-impatient)‎ . Да, я знаю, что это, вероятно, не самая простая задача, пока я не зашел так далеко, мне пришлось включить несколько исправлений ошибок для кода. Например, он не принимает CFLAGS, даже через аргумент configure --with-extra-cflags и --with-extra-cxxflags, который был создан для него: ‎[‎https://bugs.openjdk.java.net/browse/JDK-8156967‎](https://bugs.openjdk.java.net/browse/JDK-8156967)‎ . Я "исправил" его поиском/заменой CFLAGS/CXXFLAGS в скриптах make после инструкции настройки. Такое чувство, что я единственный человек на планете, составляющий‎
> 
> ‎Я прошел этап компиляции, но я не получаю ошибку компоновщика. Я думаю, что мне также нужно исправить LDFLAGS. Есть идеи, как я могу устранить следующую ошибку? Я думаю, что мне нужно‎
You're not alone , man, I'm trying to do the same and see error:
![image](https://user-images.githubusercontent.com/62550083/132176890-b2e4baac-846d-457f-ab7c-21efe87fea52.png)

**Comment by vanhauser-thc** [comment]
@LuciyVI why do you think we understand russian?

**Comment by LuciyVI** [comment]
> @LuciyVI why do you think we understand russian?

Sorry, it's reply for first massege in this issue. I did not want translate her in this reply

**Comment by vanhauser-thc** [comment]
@LuciyVI the first message is not from a russian speaking person :) (afaik)

**Comment by LuciyVI** [comment]
> @LuciyVI the first message is not from a russian speaking person :) (afaik)

Yes ! I translate first massage , when understood with this problem and reply to the translated message 
![image](https://user-images.githubusercontent.com/62550083/132191440-e7b2f14e-b4aa-49d1-ae25-fcfecb0ad35a.png)

**Comment by floyd-fuh** [comment]
I don't speak a word russian.

And btw. I never got back to the project of trying to compile JDK. Maybe I should try again.

**Comment by LuciyVI** [comment]
> I don't speak a word russian.
> 
> And btw. I never got back to the project of trying to compile JDK. Maybe I should try again.

Good Luck & Have fun :)

**Comment by LuciyVI** [comment]
I've been suffering for about a month now

> I don't speak a word russian.
> 
> And btw. I never got back to the project of trying to compile JDK. Maybe I should try again.

I've been suffering for about a month now
