### ISSUE TITLE
Performance problem, caused by commit id: df379dfcf4694

### ISSUE THREAD

**Issue by DelCoding** [vanhauser-thc/AFLplusplus#81]
i found after update to df379dfcf4694, parallel mode had a performance trouble, it was slower than single fuzzer and each cpu alse can't reach 100%(only about 50%). also, if more fuzzers, the slower each speed.

that is output of 4721617fd662787(commit id):
![4721617fd662787_good](https://user-images.githubusercontent.com/26688081/67013116-2c403480-f125-11e9-8910-698c45520786.png)

and df379dfcf4694 output:
![df379dfcf4694](https://user-images.githubusercontent.com/26688081/67013068-16cb0a80-f125-11e9-8e02-db0e6ec5f945.png)

in single fuzzer, the speed is about 3600/sec.

**Comment by hexcoder-** [comment]
Thanks for reporting!

**Comment by vanhauser-thc** [comment]
this is correct, its a 10% performance loss on my system.

I dont understand it. how can not unlinking a file but just rewriting it be slower than unlinking and recreating the file? This makes no sense at all to me. If anyone could try to explain ...

I reverted the patch in the repository. We should make another release soon :-(

@andreafioraldi fyi

**Comment by vanhauser-thc** [comment]
Also @andreafioraldi @hexcoder-  - we should add something in the test.sh script that checks for performance changes and report if +- 3% differences are detected (the +-3% is what I see on my system when I rerun fuzzing). yeah its unreliable as if an update is run in the background in parallel etc. etc. but I think we need something to catch similar issues in the future. for afl-gcc, afl-clang-fast, qemu and unicorn.

**Comment by andreafioraldi** [comment]
IMO we should separate the sh files.
Myabe the current test.sh will be test_features.sh and the new test_perf.sh.
Only the first should be runned by users after compilation to see if his
env enable all the features of afl++. The second is for us, we should run
it after each new features/commit (maybe in a CI?).

Andrea

**Comment by hexcoder-** [comment]
Yes, two scripts make sense. CI would be useful for this (and other future checks)

**Comment by vanhauser-thc** [comment]
added test/test-performance.sh script
its missing unicorn, and only does the performance testing on the base modes of afl-gcc, llvm_mode and qemu.
and the data will be different if the mutators are changed in any way.
but at least we have something ...

**Comment by andreafioraldi** [comment]
@vanhauser-thc do a new release asap

**Comment by vanhauser-thc** [comment]
@andreafioraldi @hexcoder- 

anything you want to add to the release guys?
hexcoder - I guess the gcc_plugin could be added as whitelisting is working which is already a good feature?

**Comment by hexcoder-** [comment]
Done.

**Comment by andreafioraldi** [comment]
for me we can release now, I'm investigating unicorn cache flush but there is nothing ready atm

**Comment by hexcoder-** [comment]
Great! Is it connected with a make target?

**Comment by vanhauser-thc** [comment]
I will add "make performance-test"
