### ISSUE TITLE
llvm_mode floating point split failure

### ISSUE THREAD

**Issue by andreafioraldi** [vanhauser-thc/AFLplusplus#86]
It's better to open an issue from the float related bug that I found while trying to compile ffmpeg for the issue #85 .

I attach the command line, the preprocessed C file and the generated bitcode.
Note that if I use this command line to generate the bitcode is fine (change -emit-obj to -S -emit-llvm).
[tmp.tar.gz](https://github.com/vanhauser-thc/AFLplusplus/files/3772136/tmp.tar.gz)

LLVM version 7.0.0, Ubuntu 18.04.3.

**Comment by andreafioraldi** [comment]
When compiling the produced bitcode with llc-7, I have this error:
```llc-7 af_adeclick-edd99e.ll
llc-7: error: llc-7: af_adeclick-edd99e.ll:5257:16: error: invalid cast opcode for cast from 'i1' to '<2 x i32>'
  %2431 = zext i1 %2365 to <2 x i32>, !dbg !1038
               ^
```

**Comment by andreafioraldi** [comment]
Removing this snippet seems to not solve the crash (but I'm sure that now the generated code is wrong):
```c
      case CmpInst::FCMP_ONE:
      case CmpInst::FCMP_UNE:
        /* unequal signs are unequal values */
        /* goto true branch */
        PN->addIncoming(ConstantInt::get(Int1Ty, 1), bb);
        /* unequal exponents are unequal values, too */
        PN->addIncoming(ConstantInt::get(Int1Ty, 1), signequal_bb);
        /* fractions comparison */
        PN->addIncoming(icmp_fraction_result, middle_bb);
        break;
```

**Comment by andreafioraldi** [comment]
Removing the float related code solves the segfaults but there also always other errors like the following:

```
[+] Instrumented 1093 locations (non-hardened mode, ratio 100%).
fatal error: error in backend: Cannot select: 0x55b01c3f3840: ch = br_cc 0x55b01c404ee8, setogt:ch, 0x55b01c3f3d88, 0x55b01c404a08, BasicBlock:ch< 0x55b01c4024b0>
  0x55b01c3f3d88: v4f32,ch = load<(load 16 from %ir.2889, align 4, !tbaa !838, !alias.scope !847)> 0x55b01c3f3d20, 0x55b01c3f3978, undef:i64, libavfilter/af_asoftclip.c:144:21
    0x55b01c3f3978: i64 = add 0x55b01c3f3770, 0x55b01c3d46f0, libavfilter/af_asoftclip.c:144:21
      0x55b01c3f3770: i64,ch = CopyFromReg 0x55b01c10cbd8, Register:i64 %413, libavfilter/af_asoftclip.c:144:21
        0x55b01c4040b0: i64 = Register %413
      0x55b01c3d46f0: i64 = shl 0x55b01c3f4060, Constant:i8<2>, libavfilter/af_asoftclip.c:144:21
        0x55b01c3f4060: i64,ch = CopyFromReg 0x55b01c10cbd8, Register:i64 %446, libavfilter/af_asoftclip.c:144:21
          0x55b01c3d4a30: i64 = Register %446
        0x55b01c3f37d8: i8 = Constant<2>
    0x55b01c404db0: i64 = undef
  0x55b01c404a08: v4f32 = bitcast 0x55b01c3f3c50
    0x55b01c3f3c50: v4i32 = BUILD_VECTOR Constant:i32<0>, Constant:i32<0>, Constant:i32<0>, Constant:i32<0>
      0x55b01c3d4b00: i32 = Constant<0>
      0x55b01c3d4b00: i32 = Constant<0>
      0x55b01c3d4b00: i32 = Constant<0>
      0x55b01c3d4b00: i32 = Constant<0>
In function: filter_flt
clang: error: clang frontend command failed with exit code 70 (use -v to see invocation)
clang version 7.0.0-3~ubuntu0.18.04.1 (tags/RELEASE_700/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by hexcoder-** [comment]
The source file from the tmp.tar.gz does not look preprocessed to me:
```
/usr/include/string.h:155:59: error: unknown type name 'locale_t'
extern int strcoll_l (const char *__s1, const char *__s2, locale_t __l)
                                                          ^
/usr/include/string.h:160:5: error: unknown type name 'locale_t'
                         locale_t __l) __THROW __nonnull ((2, 4));
                         ^
/usr/include/string.h:427:40: error: unknown type name 'locale_t'
extern char *strerror_l (int __errnum, locale_t __l) __THROW;
                                       ^
In file included from libavfilter/af_adeclick.c:21:
In file included from ./libavutil/audio_fifo.h:30:
./libavutil/avutil.h:344:1: error: unknown type name 'AVRational'
AVRational av_get_time_base_q(void);
^
In file included from libavfilter/af_adeclick.c:22:
./libavutil/opt.h:270:9: error: unknown type name 'AVRational'
        AVRational q;
        ^
...
```
Could you produce one, thanks.

**Comment by andreafioraldi** [comment]
IMO @hexcoder- you should use another env var to enable float splits like AFL_LLVM_LAF_SPLIT_FLOATS

**Comment by andreafioraldi** [comment]
> The source file from the tmp.tar.gz does not look preprocessed to me:
Use the sh script after replacing the `/home/andrea/Desktop/AFLplusplus` strings with your path to afl++

**Comment by hexcoder-** [comment]
Could it be, that the compiler does not support native 64 bit ints?

**Comment by andreafioraldi** [comment]
Idk, seems a laf-intel bug, it is present also if I completely remove the call to splitFPCompares

**Comment by andreafioraldi** [comment]
Have you tried to compile ffmpeg with your LLVM version?

**Comment by hexcoder-** [comment]
Please don't force me to download the whole package, preprocessed source please.

**Comment by andreafioraldi** [comment]
LOL it is also present when I force "NOT Running split-compare-pass" with an invalid bitw. The bug is present also when I only execute simplifyCompares(M)

**Comment by hexcoder-** [comment]
Regarding AFL_LLVM_LAF_SPLIT_FLOATS:

that is difficult to separate, since it uses AFL_LLVM_LAF_SPLIT_COMPARES splitting later on.
But I get your point.

**Comment by andreafioraldi** [comment]
The problem seems this code in simplyfyCompares:
```
          if (selectcmpInst->getPredicate() == CmpInst::FCMP_OGE ||
              selectcmpInst->getPredicate() == CmpInst::FCMP_UGE ||
              selectcmpInst->getPredicate() == CmpInst::FCMP_OLE ||
              selectcmpInst->getPredicate() == CmpInst::FCMP_ULE) {

            auto op0 = selectcmpInst->getOperand(0);
            auto op1 = selectcmpInst->getOperand(1);

            Type *TyOp0 = op0->getType();
            Type *TyOp1 = op1->getType();

            /* this is probably not needed but we do it anyway */
            if (TyOp0 != TyOp1) { continue; }

            fcomps.push_back(selectcmpInst);

          }```
After removing it and the call to splitFPCompares the issue does not appear anymore.

**Comment by hexcoder-** [comment]
ok, good progress. If you could provide something smaller and preprocessed, I might see what is going on. Then it is the sign extraction part of simplifyCompares(). Probably would happen with FP splitting too.
Please lets isolate it.

**Comment by andreafioraldi** [comment]
Yes, I'm trying to select two testcases cause seems two separate bugs. One when the >= and <= float comp are splitted and the other on the produced code in splitFPCompares.

**Comment by andreafioraldi** [comment]
[semplify_bug.tar.gz](https://github.com/vanhauser-thc/AFLplusplus/files/3772468/semplify_bug.tar.gz)

You have a testcase for the first bug, this is for the second.

**Comment by hexcoder-** [comment]
But I don't have **_PREPROCESSED_** source. Seems to be really difficult...

**Comment by andreafioraldi** [comment]
Oh yes sorry I thought that LLVM debug C files were already preprocessed.
Download it from https://drive.google.com/file/d/1Yl7TiWsrDcVmHMxxqC9-166JAdS6ouBo/view?usp=sharing (too large for github)

**Comment by andreafioraldi** [comment]
@hexcoder- as quick and dirty workaround to have laf-intel working I added the `AFL_LLVM_LAF_SPLIT_FLOATS` env var that enables the splitting of float comparisons when `AFL_LLVM_LAF_SPLIT_COMPARES` is also set.

**Comment by hexcoder-** [comment]
fixed with https://github.com/vanhauser-thc/AFLplusplus/commit/3ad5316dd1d7a4512b5acc17381a634a82901406. Please recheck.

**Comment by vanhauser-thc** [comment]
AFL_LLVM_LAF_SPLIT_FLOATS is a good option to have anyway.
is it fixed?

**Comment by hexcoder-** [comment]
Like I said.

The preprocessed code from @andreafioraldi  does compile now with FP splitting enabled.

The treatment of FP splitting is unchanged, but we now filter out comparisons with operands of type **vector/array of** double, float, etc.
These types are not easily splittable (for me).

**Comment by andreafioraldi** [comment]
I can't test it now, but I will do it tomorrow probably. Btw I pushed float compcov for qemu mode if you want to try it.

**Comment by andreafioraldi** [comment]
Negative, it fails again. @hexcoder- take this preprocessed C https://drive.google.com/file/d/1-zA8Vo_DyRrKxk-EKQjk4hGdSTZFGKwK/view?usp=sharing

**Comment by hexcoder-** [comment]
Thanks for testing!

**Comment by hexcoder-** [comment]
ok, the second fix is in https://github.com/vanhauser-thc/AFLplusplus/commit/38d74f0ad56a74cfed1eec04a8a46b4f8e4ec824. I could compile the whole ffmpeg with AFL_LLVM_LAF_SPLIT_COMPARES=1
and AFL_LLVM_LAF_SPLIT_FLOATS=1.
